export interface WorkbenchOptions {
    document?: import('@conduitcad/model').CadDocument;
    backend?: 'auto' | 'canvas' | 'webgl2' | 'webgpu';
    store?: import('@conduitcad/storage').ProjectStore;
    workspaceKey?: string;
    maxDocuments?: number;
}
export interface DocumentOpenOptions { context?: Record<string, any>; }
export function symbolSVG(block: any, doc: any, extra?: string): string;
export function mountWorkbench(element: any, options?: WorkbenchOptions): Workbench;
export class Workbench {
    constructor(root: any, options?: WorkbenchOptions);
    root: any;
    options: WorkbenchOptions;
    initializing: boolean;
    documents: import('@conduitcad/workspace').DocumentWorkspace<any>;
    drawingSession: import('@conduitcad/drawing').DrawingSession | null;
    blockSession: any;
    drawingOptions: Record<string, Record<string, any>>;
    doc: any;
    selection: Set<any>;
    tool: string;
    category: string;
    librarySearch: string;
    inspectorTab: string;
    currentLayer: string;
    lineStyle: string;
    gridSnap: boolean;
    objectSnap: boolean;
    ortho: boolean;
    draft: any[];
    cursor: any;
    clipboard: {
        entities: any;
        blocks: any;
        layers: any;
    };
    pointer: any;
    connectionStart: any;
    multi: boolean;
    abort: AbortController;
    solver: ConstraintSolver;
    camera: Camera;
    renderer: CadRenderer;
    store: any;
    history: History;
    input: PointerController;
    ready: Promise<this>;
    $(selector: any): any;
    initialize(params: any): Promise<this>;
    renderShell(): void;
    toolButton(tool: any, label: any, ic: any, cls?: string): string;
    bindEvents(): void;
    space: boolean;
    onClick(event: any): Promise<void>;
    suppressLibraryClick: any;
    action(action: any): Promise<void>;
    updateUI(): void;
    updateStatus(): void;
    updateHistory(): void;
    updateFrame(stats: any): void;
    rendererStatus(s: any): void;
    rendererMessage: any;
    beginBlockEdit(name: any): void;
    saveBlockEdit(close?: boolean): import("@conduitcad/model").BlockUpdateReport;
    cancelBlockEdit(): import("@conduitcad/model").BlockUpdateReport;
    selected(): any;
    eval(source: any): number;
    touch(changed?: any): void;
    edit(label: any, action: any): void;
    updateSelection(): void;
    selectEntity(id: any, focus?: boolean): void;
    setTool(tool: any): void;
    previewSymbol: import("@conduitcad/model").CadEntity;
    preview: any;
    snap: any;
    updateTools(): void;
    isMobile(): any;
    togglePanel(name: any): void;
    openPanel(name: any): void;
    closePanels(): void;
    symbolName(id: any): any;
    renderLibrary(): void;
    librarySymbolPreview(symbol: any): string;
    libraryGuide(): void;
    pickSymbol(id: any): void;
    pendingSymbol: any;
    symbolAt(id: any, x: any, y: any, tag?: boolean): import("@conduitcad/model").CadEntity;
    nextTag(id: any): string;
    placeSymbol(id: any, p: any): undefined;
    libraryPointerDown(event: any): void;
    suppressLibraryClickUntil: number;
    field(name: any, label: any, value: any, full?: boolean, unit?: string): string;
    renderInspector(): void;
    renderBaseInspector(): void;
    constraintsHTML(selected: any): string;
    onChange(event: any): void;
    setProperty(e: any, key: any, source: any): void;
    evaluateParametric(e: any): void;
    constraintsForSolve(): any[];
    solveConstraints(): void;
    lastSolve: import("@conduitcad/constraints").SolveReport;
    checkDrawing(): any[];
    nearby(p: any, tolerance?: number): any[];
    hitTest(p: any, tolerance?: number): any;
    portAt(p: any, { selectedOnly, tolerance }?: {
        selectedOnly?: boolean;
        tolerance?: number;
    }): import("@conduitcad/model").Port;
    snapPoint(p: any, exclude?: Set<any>, base?: any): any;
    connectionPoint(p: any): {
        p: {
            x: number;
            y: number;
            dx: number;
            dy: number;
            entityId: string;
        };
        ref: {
            entityId: string;
            port: string;
        };
        port: import("@conduitcad/model").Port;
    } | {
        p: import("@conduitcad/model").Port;
        ref: {
            entityId: any;
            port: string;
        };
        port: import("@conduitcad/model").Port;
    } | {
        p: any;
        ref: any;
        port?: undefined;
    };
    obstacles(): any;
    routeConnection(start: any, end: any, waypoints?: any[]): import("@conduitcad/routing").RouteResult;
    createConnector(start: any, end: any): undefined;
    reroute(changed?: any): void;
    lastRoutedIds: Set<any>;
    grips(e: any): any;
    pointerDown(p: any): void;
    shift: any;
    lastScreen: any;
    downScreen: {
        x: any;
        y: any;
    };
    drag: {
        kind: string;
        last: any;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        start?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        id: any;
        grip: any;
        original: any;
        start: {
            x: number;
            y: number;
        };
        last?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        fromSelect: boolean;
        start: {
            x: number;
            y: number;
        };
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        start: {
            x: number;
            y: number;
        };
        originals: any;
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        fromSelect?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        start?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        last: any;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        start?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        start: {
            x: number;
            y: number;
        };
        current: {
            x: number;
            y: number;
        };
        additive: any;
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        start: {
            x: number;
            y: number;
        };
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        start: {
            x: number;
            y: number;
        };
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        start?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        p: any;
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        start?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        start: any;
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        start: any;
        wasDraft: boolean;
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
    };
    pointerMove(p: any): void;
    pointerHover(p: any): void;
    hoveredPort: import("@conduitcad/model").Port;
    pointerUp(p: any): void;
    makePreview(a: any, b: any): any;
    finishShape(a: any, b: any): void;
    finishPath(): void;
    cancelGesture(): void;
    drawOverlay(ctx: any, cam: any): void;
    showContext(p: any): void;
    hideContext(): void;
    requireSelection(count?: number): any;
    deleteSelection(): void;
    duplicateSelection(): void;
    copySelection(): void;
    pasteSelection(): void;
    rotateSelection(angle: any): void;
    offsetSelection(amount: any): void;
    trimSelection(extend?: boolean): void;
    filletSelection(radius: any): void;
    explodeSelection(): void;
    makeSymbolDialog(): void;
    constraintDialog(): void;
    parametersDialog(): void;
    precisionDialog(): void;
    lineStylesDialog(): void;
    moreDialog(shapesOnly?: boolean): void;
    editText(e: any): void;
    openModal(title: any, body: any, { confirm, onConfirm, wide }?: {
        confirm?: any;
        onConfirm?: any;
        wide?: boolean;
    }): void;
    modal: HTMLDivElement;
    previousFocus: Element;
    modalConfirm: () => Promise<void>;
    closeModal(): void;
    ask(title: any, fields: any, onConfirm: any): void;
    toast(message: any, error?: boolean): void;
    toastTimer: number;
    newDialog(): void;
    newDocument(kind: string): Promise<import("@conduitcad/workspace").DocumentSession<import("@conduitcad/model").CadDocument>>;
    openDocument(document: import("@conduitcad/model").CadDocument, options?: DocumentOpenOptions): import("@conduitcad/workspace").DocumentSession<import("@conduitcad/model").CadDocument>;
    activateDocument(id: string): import("@conduitcad/workspace").DocumentSession<import("@conduitcad/model").CadDocument>;
    closeDocument(id?: string): void | Promise<void>;
    saveAllDocuments(): Promise<import("@conduitcad/workspace").WorkspaceManifest>;
    scheduleRecovery(): void;
    documentChanged(): void;
    basename(): any;
    exportDialog(): void;
    doExport(format: any): Promise<void>;
    openFiles(files: any): Promise<any[]>;
    openFile(file: any): any;
    documentImportQueue: any;
    importFile(file: any): Promise<any>;
    commandDialog(): void;
    executeCommand(source: any): void;
    keyDown(e: any): void;
    helpDialog(): void;
    dispose(): Promise<unknown>;
}
import { ConstraintSolver } from '@conduitcad/constraints';
import { Camera } from '@conduitcad/renderer';
import { CadRenderer } from '@conduitcad/renderer';
import { History } from '@conduitcad/history';
import { PointerController } from '@conduitcad/input';
