export function symbolSVG(block: any, doc: any, extra?: string): string;
export function mountWorkbench(element: any, options?: {}): Workbench;
export class Workbench {
    beginBlockEdit(name: string): void;
    saveBlockEdit(close?: boolean): import("@conduitcad/model").BlockUpdateReport | null;
    cancelBlockEdit(): void;
    constructor(root: any, options?: {});
    root: any;
    options: {};
    doc: any;
    selection: Set<any>;
    tool: string;
    drawingSession: import("@conduitcad/drawing").DrawingSession | null;
    drawingOptions?: Partial<Record<import("@conduitcad/drawing").DrawingToolId, import("@conduitcad/drawing").DrawingOptions>>;
    category: string;
    librarySearch: string;
    inspectorTab: string;
    currentLayer: string;
    lineStyle: string;
    gridSnap: boolean;
    objectSnap: boolean;
    ortho: boolean;
    draft: any[];
    cursor: any;
    clipboard: {
        entities: any;
        blocks: any;
    };
    pointer: any;
    connectionStart: any;
    multi: boolean;
    abort: AbortController;
    solver: ConstraintSolver;
    camera: Camera;
    renderer: CadRenderer;
    store: ProjectStore;
    history: History;
    input: PointerController;
    ready: Promise<this>;
    $(selector: any): any;
    initialize(params: any): Promise<this>;
    renderShell(): void;
    toolButton(tool: any, label: any, ic: any, cls?: string): string;
    bindEvents(): void;
    space: boolean;
    onClick(event: any): Promise<void>;
    suppressLibraryClick: boolean;
    action(action: any): Promise<void>;
    updateUI(): void;
    updateStatus(): void;
    updateHistory(): void;
    updateFrame(stats: any): void;
    rendererStatus(s: any): void;
    rendererMessage: any;
    selected(): any;
    eval(source: any): any;
    touch(changed?: any): void;
    edit(label: any, action: any): void;
    updateSelection(): void;
    selectEntity(id: any, focus?: boolean): void;
    setTool(tool: any): void;
    previewSymbol: {
        id: string;
        type: any;
        layer: string;
    };
    preview: import("@conduitcad/model").CadEntity | import("@conduitcad/model").PolylineEntity;
    snap: any;
    updateTools(): void;
    isMobile(): boolean;
    togglePanel(name: any): void;
    openPanel(name: any): void;
    closePanels(): void;
    symbolName(id: any): any;
    renderLibrary(): void;
    pickSymbol(id: any): void;
    pendingSymbol: any;
    symbolAt(id: any, x: any, y: any, tag?: boolean): {
        id: string;
        type: any;
        layer: string;
    };
    nextTag(id: any): string;
    placeSymbol(id: any, p: any): undefined;
    libraryPointerDown(event: any): void;
    field(name: any, label: any, value: any, full?: boolean, unit?: string): string;
    renderInspector(): void;
    constraintsHTML(selected: any): string;
    onChange(event: any): void;
    setProperty(e: any, key: any, source: any): void;
    evaluateParametric(e: any): void;
    solveConstraints(): void;
    lastSolve: {
        converged: boolean;
        iterations: number;
        residual: number;
        variables: number;
        equations: number;
        status: string;
        rolledBack: boolean;
    };
    checkDrawing(): any[];
    nearby(p: any, tolerance?: number): any[];
    hitTest(p: any, tolerance?: number): any;
    portAt(p: any, { selectedOnly, tolerance }?: {
        selectedOnly?: boolean;
        tolerance?: number;
    }): import("@conduitcad/model").Port;
    snapPoint(p: any, exclude?: Set<any>, base?: any): any;
    connectionPoint(p: any): {
        p: {
            x: number;
            y: number;
            dx: number;
            dy: number;
            entityId: string;
        };
        ref: {
            entityId: string;
            port: string;
        };
        port: import("@conduitcad/model").Port;
    } | {
        p: import("@conduitcad/model").Port;
        ref: {
            entityId: any;
            port: string;
        };
        port: import("@conduitcad/model").Port;
    } | {
        p: any;
        ref: any;
        port?: undefined;
    };
    obstacles(): any;
    routeConnection(start: any, end: any, waypoints?: any[]): {
        points: any[];
        status: string;
        visited: number;
    };
    createConnector(start: any, end: any): undefined;
    reroute(changed?: any): void;
    lastRoutedIds: Set<any>;
    grips(e: any): any;
    pointerDown(p: any): void;
    shift: any;
    lastScreen: any;
    downScreen: {
        x: any;
        y: any;
    };
    drag: {
        kind: string;
        last: any;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        start?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        id: any;
        grip: any;
        original: any;
        start: {
            x: number;
            y: number;
        };
        last?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        fromSelect: boolean;
        start: {
            x: number;
            y: number;
        };
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        start: {
            x: number;
            y: number;
        };
        originals: any;
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        fromSelect?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        start?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        last: any;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        start?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        start: {
            x: number;
            y: number;
        };
        current: {
            x: number;
            y: number;
        };
        additive: any;
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        start: {
            x: number;
            y: number;
        };
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        start: {
            x: number;
            y: number;
        };
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        start?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        p: any;
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        start?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        wasDraft?: undefined;
    } | {
        kind: string;
        start: any;
        wasDraft: boolean;
        last?: undefined;
        id?: undefined;
        grip?: undefined;
        original?: undefined;
        fromSelect?: undefined;
        originals?: undefined;
        current?: undefined;
        additive?: undefined;
        p?: undefined;
    };
    pointerMove(p: any): void;
    pointerHover(p: any): void;
    hoveredPort: import("@conduitcad/model").Port;
    pointerUp(p: any): void;
    makePreview(a: any, b: any): import("@conduitcad/model").CadEntity;
    finishShape(a: any, b: any): void;
    finishPath(): void;
    cancelGesture(): void;
    drawOverlay(ctx: any, cam: any): void;
    showContext(p: any): void;
    hideContext(): void;
    requireSelection(count?: number): any;
    deleteSelection(): void;
    duplicateSelection(): void;
    copySelection(): void;
    pasteSelection(): void;
    rotateSelection(angle: any): void;
    offsetSelection(amount: any): void;
    trimSelection(extend?: boolean): void;
    filletSelection(radius: any): void;
    explodeSelection(): void;
    makeSymbolDialog(): void;
    constraintDialog(): void;
    parametersDialog(): void;
    precisionDialog(): void;
    lineStylesDialog(): void;
    moreDialog(shapesOnly?: boolean): void;
    editText(e: any): void;
    openModal(title: any, body: any, { confirm, onConfirm, wide }?: {
        confirm?: any;
        onConfirm?: any;
        wide?: boolean;
    }): void;
    modal: HTMLDivElement;
    previousFocus: Element;
    modalConfirm: () => Promise<void>;
    closeModal(): void;
    ask(title: any, fields: any, onConfirm: any): void;
    toast(message: any, error?: boolean): void;
    toastTimer: number;
    newDialog(): void;
    newDocument(kind: any): Promise<void>;
    basename(): any;
    exportDialog(): void;
    doExport(format: any): Promise<void>;
    openFile(file: any): Promise<void>;
    commandDialog(): void;
    executeCommand(source: any): void;
    keyDown(e: any): void;
    helpDialog(): void;
    dispose(): void;
}
import { ConstraintSolver } from '@conduitcad/constraints';
import { Camera } from '@conduitcad/renderer';
import { CadRenderer } from '@conduitcad/renderer';
import { ProjectStore } from '@conduitcad/storage';
import { History } from '@conduitcad/history';
import { PointerController } from '@conduitcad/input';
