"""Actual style, material, document and adaptive display interactions."""
import json,base64
from playwright.sync_api import sync_playwright
from PIL import Image
from render_support import Harness,launch,bounded,frame,NATIVE,OUT
checks=[];errors=[];h=Harness()
def ok(name,value):
 assert value,name
 checks.append({'name':name,'passed':True});print(name,flush=True)
def action(page,a):page.evaluate('(a)=>conduit.action(a)',a)
def close(page):page.evaluate('conduit.closeModal()')
def summary(page,text):page.locator('summary').filter(has_text=text).click()
def keep(page):page.get_by_role('button',name='Keep display',exact=True).click();page.wait_for_function('!conduit.modal')
try:
 with sync_playwright() as p:
  browser=launch(p)
  for width,height,touch in [(1440,980,False),(320,568,True),(390,844,True),(844,390,True),(1024,768,True)]:
   context=browser.new_context(viewport={'width':width,'height':height},has_touch=touch,is_mobile=touch,device_scale_factor=1,accept_downloads=True)
   page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)));h.load(page)
   prefix=f'{width}x{height} '
   page.evaluate('window.beforeStyleDoc=JSON.stringify(conduit.doc);window.beforeStyleCamera=JSON.stringify(conduit.model3d.camera.snapshot());window.before2D=JSON.stringify({x:conduit.camera.x,y:conduit.camera.y,scale:conduit.camera.scale})')
   action(page,'3d-display')
   ok(prefix+'sixteen labeled style choices',page.locator('[data-display-style]').count()==16)
   ok(prefix+'preview panel and confirmation stay inside viewport',bounded(page,'.display3d-dialog') and bounded(page,'.display3d-dialog .modal-foot'))
   ok(prefix+'live preview does not blur the model',page.locator('.display3d-backdrop').evaluate("e=>getComputedStyle(e).backdropFilter==='none'"))
   if touch:ok(prefix+'style targets are touch-sized',page.locator('[data-display-style]').evaluate_all('es=>es.every(e=>e.getBoundingClientRect().height>=44)'))
   page.locator('#display3d-search').fill('hidden')
   ok(prefix+'search finds multiple hidden-line variants',page.locator('[data-display-style]:visible').count()>=3)
   page.locator('#display3d-search').fill('not-an-existent-style')
   ok(prefix+'empty search has feedback',page.locator('.display3d-no-results').is_visible())
   page.locator('#display3d-search').fill('')
   page.locator('[data-display-style="xray"]').click()
   ok(prefix+'style click previews without editing the drawing',page.evaluate('conduit.model3d.renderer.style==="xray"&&JSON.stringify(conduit.doc)===beforeStyleDoc'))
   close(page)
   ok(prefix+'Cancel restores original display and camera',page.evaluate('conduit.model3d.renderer.style==="shaded-edges"&&JSON.stringify(conduit.model3d.camera.snapshot())===beforeStyleCamera'))
   action(page,'3d-display');page.locator('[data-display-style="conceptual"]').click();keep(page)
   ok(prefix+'Keep commits document-specific view state, not CAD geometry',page.evaluate('conduit.model3dDisplay.style==="conceptual"&&JSON.stringify(conduit.doc)===beforeStyleDoc'))
   page.evaluate('window.uploadBefore=conduit.model3d.renderer.uploads;conduit.model3d.renderer.camera.orbit(5,3);conduit.model3d.renderer.draw()')
   ok(prefix+'camera navigation preserves uploaded geometry',page.evaluate('conduit.model3d.renderer.uploads===uploadBefore'))
   action(page,'3d-display');summary(page,'Edges and silhouettes');page.locator('[data-display-setting="edgeWidth"]').fill('2.5');page.locator('[data-display-setting="edgeWidth"]').press('Tab')
   ok(prefix+'line-width preference is live and uniform-only',page.evaluate('conduit.model3d.renderer.settings.edgeWidth===2.5&&conduit.model3d.renderer.uploads===uploadBefore'))
   close(page)
   ok(prefix+'secondary live preferences revert on Cancel',page.evaluate('conduit.model3d.renderer.settings.edgeWidth===1'))
   page.screenshot(path=str(OUT/f'render-styles-{width}-workspace.png'))
   action(page,'3d-display');page.screenshot(path=str(OUT/f'render-styles-{width}-panel.png'))
   if width<=600 or height<=500:
    page.evaluate('window.cameraBeforePeek=JSON.stringify(conduit.model3d.camera.snapshot())')
    page.locator('#display3d-peek').click();page.wait_for_timeout(80)
    ok(prefix+'compact live preview hides options while retaining style control',not page.locator('.display3d-dialog .modal-body').is_visible() and bounded(page,'#display3d-quick-style'))
    page.locator('#display3d-quick-style').select_option('realistic')
    ok(prefix+'compact style selector changes actual shading',page.evaluate('conduit.model3d.renderer.style==="realistic"'))
    page.screenshot(path=str(OUT/f'render-styles-{width}-peek.png'))
    page.locator('#display3d-peek').click();page.wait_for_timeout(30)
    ok(prefix+'leaving comparison restores exact working camera',page.evaluate('JSON.stringify(conduit.model3d.camera.snapshot())===cameraBeforePeek'))
   close(page)
   action(page,'3d-2d')
   ok(prefix+'return to 2D retains drafting camera and controls',page.evaluate('conduit.viewMode==="2d"&&JSON.stringify({x:conduit.camera.x,y:conduit.camera.y,scale:conduit.camera.scale})===before2D'))
   action(page,'mode-3d');ok(prefix+'return to 3D retains chosen style',page.evaluate('conduit.model3d.renderer.style==="conceptual"'))
   context.close()
  context=browser.new_context(viewport={'width':1440,'height':1000},accept_downloads=True);page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)));h.load(page)
  action(page,'3d-display');summary(page,'Custom presets and portable defaults');page.locator('#display3d-preset-name').fill('Inspection edges');page.locator('#display3d-save-default').check();page.locator('[data-display-style="wireframe-hidden"]').click();keep(page)
  ok('named preset and drawing default are portable metadata',page.evaluate('conduit.doc.metadata.display3d.style==="wireframe-hidden"&&conduit.doc.metadata.displayPresets3d[0].name==="Inspection edges"'))
  page.evaluate('window.docA=conduit.documents.activeId;conduit.model3d.renderer.section={normal:{x:0,y:0,z:1},offset:12};conduit.model3d.saveView()')
  page.evaluate("conduit.newDocument('3d:extrusion-study')")
  ok('new document does not inherit another document display style',page.evaluate('conduit.model3d.renderer.style==="shaded-edges"&&conduit.model3d.renderer.section===null'))
  page.locator('[role=tab][data-document-id="'+page.evaluate('docA')+'"]').click()
  ok('tab return restores style and section plane independently',page.evaluate('conduit.model3d.renderer.style==="wireframe-hidden"&&conduit.model3d.renderer.section.offset===12'))
  page.evaluate('conduit.model3d.renderer.section=null;conduit.model3d.saveView()')
  page.evaluate("conduit.selectEntity(conduit.doc.entities.find(e=>e.type==='MESH').id);window.materialId=conduit.selected()[0].id")
  page.evaluate("conduit.options.modelingInteraction='dialog'");action(page,'3d-appearance');page.locator('#material3d-preset').select_option('copper');page.locator('#material3d-roughness').fill('0.3');page.get_by_role('button',name='Apply appearance',exact=True).click()
  ok('material form updates native color and coefficients atomically',page.evaluate('conduit.doc.entities.find(e=>e.id===materialId).color==="#c88455"&&conduit.doc.entities.find(e=>e.id===materialId).appearance3d.roughness===.3'))
  ok('material assignment exposes realistic shading',page.evaluate('conduit.model3d.renderer.style==="realistic"'))
  action(page,'3d-undo');ok('undo restores original appearance',page.evaluate('!conduit.doc.entities.find(e=>e.id===materialId).appearance3d'))
  action(page,'3d-redo');ok('redo restores material coefficients',page.evaluate('conduit.doc.entities.find(e=>e.id===materialId).appearance3d.metallic===1'))
  page.evaluate("conduit.selectEntity(materialId)");page.evaluate("conduit.options.modelingInteraction='dialog'");action(page,'3d-appearance');page.locator('#material3d-roughness').fill('-1');page.get_by_role('button',name='Apply appearance',exact=True).click()
  ok('invalid material values leave the document unmodified',page.locator('.error-text').inner_text()!='' and page.evaluate('conduit.doc.entities.find(e=>e.id===materialId).appearance3d.roughness===.3'))
  close(page)
  page.evaluate("conduit.executeCommand('VSCURRENT hidden')")
  ok('CAD display command uses the actual mode registry',page.evaluate('conduit.model3d.renderer.style==="hidden"'))
  action(page,'3d-display');summary(page,'Custom presets and portable defaults');page.locator('[data-display-preset="0"]').click()
  ok('custom preset reloads validated saved fields',page.evaluate('conduit.model3d.renderer.style==="wireframe-hidden"'))
  close(page)
  action(page,'3d-rendering-study')
  ok('material study opens an independent editable drawing',page.evaluate('conduit.doc.entities.length===19&&conduit.doc.entities.every(e=>!!e.feature3d)&&conduit.model3d.renderer.style==="realistic"'))
  ok('portable default restores ground, shadows and AO',page.evaluate('conduit.model3d.renderer.settings.ground&&conduit.model3d.renderer.settings.shadows&&conduit.model3d.renderer.settings.ambientOcclusion'))
  page.evaluate('conduit.model3d.renderer.draw()');page.screenshot(path=str(OUT/'render-material-study.png'))
  with page.expect_download() as download:
   action(page,'3d-capture')
  download.value.save_as(str(OUT/'render-viewport-export.png'))
  image=Image.open(OUT/'render-viewport-export.png');expected=page.evaluate('({w:conduit.model3d.renderer.canvas.width,h:conduit.model3d.renderer.canvas.height})')
  ok('actual viewport PNG download has renderer dimensions',image.size==(expected['w'],expected['h']))
  page.evaluate('conduit.saveAllDocuments()')
  ok('workspace snapshot contains per-document display and sections',page.evaluate('conduit.documents.sessions.every(s=>!s.context.model3dDisplay||typeof s.context.model3dDisplay.style==="string")'))
  ok('no uncaught browser errors',not errors)
  context.close();browser.close()
finally:
 h.close();(OUT/'render-styles-browser.json').write_text(json.dumps({'checks':checks,'errors':errors,'origin':'localhost'if NATIVE else'opaque with explicit memory storage adapter','renderer':'Canvas software depth','physicalDevice':False},indent=2))
print(f'{len(checks)} render-style browser assertions passed.')
