"""Real-origin graphical block authoring, shared inserts, calculations and sketch UI."""
import functools, http.server, json, os, shutil, threading
from pathlib import Path
from playwright.sync_api import sync_playwright
import ezdxf
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'artifacts'; OUT.mkdir(exist_ok=True)
checks=[]; errors=[]
def ok(name,value):
    assert value,name
    checks.append({'name':name,'passed':True})
class Handler(http.server.SimpleHTTPRequestHandler):
    def log_message(self,*args):pass
server=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(Handler,directory=str(ROOT/'dist')))
threading.Thread(target=server.serve_forever,daemon=True).start()
try:
  with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_EXECUTABLE') or shutil.which('chromium'),headless=True,args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1440,'height':1000},accept_downloads=True)
    page.on('pageerror',lambda e:errors.append(str(e)))
    if os.environ.get('CONDUIT_TEST_ORIGIN')=='localhost': page.goto(f'http://127.0.0.1:{server.server_port}/?fresh=1&renderer=canvas')
    else: page.set_content((ROOT/'dist/ConduitCAD.html').read_text().replace("mountWorkbench(document.getElementById('app'))","mountWorkbench(document.getElementById('app'),{backend:'canvas'})"))
    page.wait_for_function('document.documentElement.dataset.ready === "true"')
    page.evaluate("""()=>{conduit.store.save=async()=>{};conduit.store.schedule=()=>{};
      const edge={id:'edge',type:'LINE',layer:'0',a:{x:0,y:0},b:{x:100,y:0}};
      conduit.doc.blocks={Part:{name:'Part',base:{x:0,y:0},entities:[edge],ports:[{name:'out',x:100,y:0,dx:1,dy:0}]},Parent:{name:'Parent',base:{x:0,y:0},entities:[{id:'nested',type:'INSERT',block:'Part',x:0,y:0,sx:1,sy:1}]}};
      conduit.doc.entities=[{id:'a',type:'INSERT',block:'Part',layer:'0',x:0,y:0,sx:1,sy:1},{id:'b',type:'INSERT',block:'Part',layer:'0',x:300,y:0,sx:1,sy:1},{id:'c',type:'INSERT',block:'Parent',layer:'0',x:600,y:0,sx:1,sy:1}];
      conduit.doc.constraints=[];conduit.selection=new Set(['a']);conduit.history.clear();conduit.touch();conduit.updateUI();conduit.renderer.fit();} """)
    page.locator('[data-action="block-edit"]').click()
    ok('graphical block editor opens isolated native geometry',page.evaluate("!!conduit.blockSession && conduit.doc.entities.length===1 && conduit.doc.entities[0].type==='LINE'"))
    page.evaluate("conduit.selectEntity('edge')")
    page.locator('[data-prop="length"]').fill('160');page.locator('[data-prop="length"]').press('Tab')
    ok('property edit changes block draft without touching source',page.evaluate("conduit.doc.entities[0].b.x===160 && conduit.blockSession.parentDocument.blocks.Part.entities[0].b.x===100"))
    page.locator('[data-action="block-save-close"]').click()
    ok('save updates shared definition and preserves all insert identities',page.evaluate("!conduit.blockSession && conduit.doc.blocks.Part.entities[0].b.x===160 && conduit.doc.entities.map(e=>e.id).join()==='a,b,c'"))
    ok('nested insert renderer rebuilds after master save',page.evaluate("conduit.renderer.scene.items.find(e=>e.id==='c').maxX>=760"))
    page.evaluate('conduit.history.undo()')
    ok('shared block update is one document undo transaction',page.evaluate("conduit.doc.blocks.Part.entities[0].b.x===100"))
    page.evaluate('conduit.history.redo()')
    ok('redo restores shared block edit',page.evaluate("conduit.doc.blocks.Part.entities[0].b.x===160"))
    page.locator('[data-action="block-edit"]').click()
    page.evaluate("conduit.executeCommand('LINE 0,20 100,20')")
    ok('native drawing tools add geometry inside block editor',page.evaluate('conduit.doc.entities.length===2'))
    page.evaluate('conduit.cancelBlockEdit()')
    ok('discard leaves previously saved master untouched',page.evaluate("conduit.doc.blocks.Part.entities.length===1"))
    page.locator('[data-action="block-edit"]').click()
    page.evaluate("conduit.selectEntity('edge')")
    page.locator('[data-action="block-author"]').first.click()
    page.locator('[data-block-field="name"]').fill('Length')
    page.locator('[data-block-field="default"]').fill('160')
    page.locator('[data-block-field="min"]').fill('20')
    page.locator('[data-block-field="max"]').fill('500')
    page.locator('#author-add-parameter').click()
    page.locator('#author-add-action').click()
    ok('graphical author attaches stretch to selected entity IDs',page.evaluate("JSON.parse(document.querySelector('#author-schema').value).actions[0].entities[0]==='edge'"))
    page.locator('[data-action="modal-confirm"]').click()
    ok('behavior author validates and applies schema without JSON-only workflow',page.evaluate("conduit.doc.blockEditing.dynamic.parameters[0].name==='Length'"))
    page.locator('[data-action="block-test"]').click()
    page.locator('[data-dynamic="Length"]').fill('220');page.locator('[data-dynamic="Length"]').press('Tab')
    ok('test-block inspector evaluates scratch parameters',page.evaluate("conduit.selected()[0].dynamicParameters.Length===220"))
    page.locator('[data-action="block-test-close"]').click()
    ok('test block does not mutate master draft',page.evaluate("conduit.doc.entities[0].b.x===160"))
    page.locator('[data-action="block-save-close"]').click()
    ok('saved behavior appears on every existing reference',page.locator('[data-dynamic="Length"]').count()==1)
    page.locator('[data-dynamic="Length"]').fill('240');page.locator('[data-dynamic="Length"]').press('Tab')
    ok('insert-specific parameters remain independent after shared authoring',page.evaluate("conduit.doc.entities[0].dynamicParameters.Length===240 && !conduit.doc.entities[1].dynamicParameters"))
    page.locator('[data-action="block-edit"]').click()
    page.locator('[data-action="block-settings"]').click()
    page.locator('[data-block-field="x"]').fill('10')
    page.locator('[data-action="modal-confirm"]').click()
    ok('base point is editable in block workspace',page.evaluate('conduit.doc.blockEditing.base.x===10'))
    page.locator('[data-action="block-attribute"]').click()
    page.locator('[data-field="tag"]').fill('PART_NUMBER')
    page.locator('[data-field="text"]').fill('PN-001')
    page.locator('[data-action="modal-confirm"]').click()
    ok('attribute definition is authored as native ATTDEF',page.evaluate("conduit.doc.entities.some(e=>e.type==='ATTDEF'&&e.tag==='PART_NUMBER')"))
    page.locator('[data-action="block-save-close"]').click()
    ok('attribute synchronization creates values on all direct inserts',page.evaluate("conduit.doc.entities.filter(e=>e.block==='Part').every(e=>e.attributes[0].text==='PN-001')"))
    page.evaluate("conduit.selection.clear();conduit.updateUI();conduit.action('parametric-demo')")
    ok('fully parametric example has driving and reference constraints',page.evaluate('conduit.doc.constraints.length===8 && conduit.lastSolve.converged'))
    page.evaluate("conduit.action('parameters')")
    row=page.locator('.param-row').filter(has=page.locator('input.param-name[value="bracketWidth"]'))
    row.locator('.param-expression').fill('200')
    ok('parameter inspector previews evaluated expression values',row.locator('output').inner_text()=='200')
    page.locator('[data-action="modal-confirm"]').click()
    ok('parameter changes re-solve driving dimensions',page.evaluate("Math.abs(conduit.doc.entities.find(e=>e.id===conduit.doc.constraints[2].entities[0]).b.x-conduit.doc.entities.find(e=>e.id===conduit.doc.constraints[2].entities[0]).a.x-200)<.001"))
    page.evaluate("conduit.action('solver-report')")
    ok('solve diagnostics show rank DOF and reference measurements',page.locator('.solve-summary').first.inner_text().find('rank')>=0 and page.locator('[data-constraint-row]').count()==8)
    page.screenshot(path=str(OUT/'parametric-solver-diagnostics.png'))
    page.evaluate('conduit.closeModal()')
    page.evaluate("conduit.action('calculated-text')")
    page.locator('[data-field="expression"]').fill('hypot(bracketWidth,bracketHeight)')
    page.locator('[data-action="modal-confirm"]').click()
    ok('calculated annotation evaluates allowed math functions',page.evaluate("conduit.selected()[0].calculation.value>211 && conduit.selected()[0].calculation.value<213"))
    page.locator('[data-prop="calculationPrecision"]').fill('2');page.locator('[data-prop="calculationPrecision"]').press('Tab')
    ok('calculated text exposes editable formula and formatting properties',page.locator('[data-prop="calculationExpression"]').count()==1 and page.evaluate('conduit.selected()[0].calculation.precision===2'))
    old=page.evaluate('conduit.selected()[0].text')
    page.evaluate("conduit.executeCommand('PARAM bracketHeight=100')")
    ok('calculated drawing annotation automatically updates',page.evaluate('conduit.selected()[0].text')!=old)
    page.evaluate("conduit.selection.clear();conduit.showConstraintAnnotations=true;conduit.touch();conduit.renderer.fit();conduit.updateUI()")
    page.wait_for_timeout(150);page.screenshot(path=str(OUT/'parametric-constraint-annotations.png'))
    ok('constraint labels expose solved values and reference state',page.evaluate("conduit.constraintLabels.some(a=>a.reference)&&conduit.constraintLabels.some(a=>Math.abs(a.value-200)<.001)"))
    page.evaluate("conduit.action('export')")
    with page.expect_download() as download:page.locator('[data-export="dxf-binary"]').click()
    file=OUT/'parametric-authoring-browser.dxf';download.value.save_as(str(file));doc=ezdxf.readfile(file);audit=doc.audit()
    ok('edited block and parameterized design download opens independently',not audit.errors and not audit.fixes)
    page.evaluate('conduit.closeModal()')
    page.evaluate("conduit.selectEntity('a')")
    page.locator('[data-attribute]').first.fill('USER-PART')
    page.locator('[data-attribute]').first.press('Tab')
    ok('instance attribute values are editable independently',page.evaluate("conduit.doc.entities.find(e=>e.id==='a').attributes[0].text==='USER-PART' && conduit.doc.entities.find(e=>e.id==='b').attributes[0].text==='PN-001'"))
    page.evaluate("conduit.executeCommand('LINE 0,-100 100,-100');conduit.selectEntity(conduit.doc.entities.at(-1).id)")
    source_id=page.evaluate('conduit.selected()[0].id')
    page.locator('[data-action="auto-constrain"]').click()
    ok('automatic constraints are created through the graphical inspector',page.evaluate('id=>conduit.doc.constraints.some(c=>c.entities?.includes(id)&&c.type==="horizontal")',source_id))
    page.locator('[data-action="dimension-source"]').click()
    page.locator('[data-action="dimension-drive"]').click()
    page.locator('[data-field="value"]').fill('bracketWidth * 1.5')
    page.locator('[data-action="modal-confirm"]').click()
    ok('native associated dimension drives geometry by expression',page.evaluate('id=>{const e=conduit.doc.entities.find(e=>e.id===id);return Math.abs(Math.hypot(e.b.x-e.a.x,e.b.y-e.a.y)-300)<.001}',source_id))
    ok('native dimension witnesses regenerate after the driving solve',page.evaluate('Math.abs(conduit.selected()[0].b.x-conduit.selected()[0].a.x-300)<.001'))
    page.evaluate("conduit.action('blocks')")
    page.locator('#manager-name').fill('NewGraphicalBlock')
    page.locator('#manager-create').click()
    ok('block manager creates and opens a clean authoring canvas',page.evaluate('!!conduit.blockSession && !conduit.modal && conduit.doc.entities.length===0'))
    page.evaluate("conduit.executeCommand('LINE 0,0 30,0')")
    page.locator('.block-editor-bar [data-action="block-save-close"]').click()
    page.evaluate("conduit.action('blocks')")
    page.locator('#block-name').select_option('NewGraphicalBlock')
    page.locator('#manager-insert').click()
    ok('block manager inserts an authored definition as a native reference',page.evaluate("conduit.selected()[0].type==='INSERT'&&conduit.selected()[0].block==='NewGraphicalBlock'"))
    page.evaluate("conduit.action('blocks')")
    page.locator('#block-name').select_option('Part')
    page.locator('[data-action="modal-confirm"]').click()
    ok('manager edit closes modal and exposes the canvas',page.evaluate('!!conduit.blockSession && !conduit.modal'))
    page.evaluate('conduit.cancelBlockEdit()')
    page.set_viewport_size({'width':390,'height':844})
    page.evaluate("conduit.selectEntity('a');conduit.openPanel('inspector')")
    page.evaluate("conduit.mobileMedia.dispatchEvent(new Event('change'))")
    ok('queued breakpoint update preserves the explicitly opened property sheet',page.evaluate("document.querySelector('.inspector').classList.contains('open')&&!document.querySelector('.inspector').inert"))
    page.locator('[data-action="block-edit"]').click()
    ok('mobile block editor provides scrollable 44px action targets',page.locator('.block-editor-bar [data-action="block-save"]').bounding_box()['height']>=44)
    page.evaluate("conduit.selectEntity('edge');conduit.openPanel('inspector')")
    page.wait_for_timeout(150);page.screenshot(path=str(OUT/'parametric-mobile-block-editor.png'))
    ok('mobile block editor does not overflow the document',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    page.locator('[data-prop="length"]').fill('170');page.locator('[data-prop="length"]').press('Tab')
    page.evaluate('conduit.closePanels()')
    page.locator('.block-editor-bar [data-action="block-save-close"]').click()
    ok('shared saves keep instance-specific attribute text',page.evaluate("conduit.doc.entities.find(e=>e.id==='a').attributes[0].text==='USER-PART'"))
    ok('mobile block save refreshes live definition',page.evaluate("!conduit.blockSession && conduit.doc.blocks.Part.entities[0].b.x===170"))
    ok('no uncaught JavaScript errors',not errors)
    browser.close()
finally:
    server.shutdown();server.server_close()
    (OUT/'browser-parametric.json').write_text(json.dumps({'checks':checks,'passed':len(checks),'errors':errors,'backend':'Canvas 2D','physicalDevice':False,'origin':os.environ.get('CONDUIT_TEST_ORIGIN','standalone'),'storage':'save/schedule stubbed for deterministic transactions'},indent=2))
print(json.dumps({'passed':len(checks),'errors':errors},indent=2))
