"""Actual default non-modal 3D authoring. Local memory-storage adapter is explicit;
CI uses localhost. Geometry/history are not mocked; not physical-device qualification.
"""
import json, os
from playwright.sync_api import sync_playwright
from render_support import Harness, launch, bounded, OUT, NATIVE
checks=[];errors=[];h=Harness();BACKEND=os.environ.get('VISUAL_TEST_BACKEND','canvas')
def ok(name,value):
 assert value,name
 checks.append({'name':name,'passed':True});print(name,flush=True)
def ev(page,js,arg=None):return page.evaluate(js,arg)
def wait(page,milliseconds=40):
 # Geometry and ARIA controls refresh at animation-frame boundaries, not fixed GPU deadlines.
 page.wait_for_timeout(milliseconds)
 page.wait_for_function('!globalThis.conduit?.model3d?.visual?.frame',timeout=15000)
def action(page,a):ev(page,'a=>conduit.action(a)',a);wait(page,45)
def ready(page):page.wait_for_function('conduit.model3d.visual.session && (conduit.model3d.visual.session.preview || conduit.model3d.visual.session.error)');wait(page,35)
def field(page,name,value):
 loc=page.locator(f'[data-visual-field="{name}"]');loc.scroll_into_view_if_needed();loc.click();inp=page.locator('.visual3d-entry input');inp.fill(str(value));inp.press('Enter');wait(page,55)
def option(page,name,value):
 if page.locator('.visual3d-options').is_hidden():page.locator('[data-visual-command=options]').click()
 loc=page.locator(f'[data-visual-option="{name}"]');loc.scroll_into_view_if_needed()
 if loc.evaluate('e=>e.tagName')=='SELECT':loc.select_option(str(value))
 else:loc.fill(str(value));loc.press('Tab')
 wait(page,50)
def apply(page):
 page.locator('[data-visual-command=apply]').click();wait(page,50)
 assert ev(page,'!conduit.model3d.visual.active'),page.locator('.visual3d-error').inner_text()
def cancel(page):
 if ev(page,'conduit.model3d.visual.active'):page.locator('[data-visual-command=cancel]').click()
 wait(page,20)
def blank(page):
 cancel(page);ev(page,"async()=>{await conduit.newDocument('blank');await conduit.action('mode-3d');await conduit.model3d.ready;conduit.model3d.camera.view('iso');conduit.model3d.camera.target={x:25,y:20,z:15};conduit.model3d.camera.height=220;conduit.model3d.changedView()}");wait(page,50)
def create_box(page,w=100,d=80,z=40):
 action(page,'3d-op-box');ready(page)
 for name,value in [('x',0),('y',0),('z',0),('width',w),('depth',d),('height',z)]:field(page,name,value)
 apply(page);ev(page,'window.plateId=conduit.doc.entities.at(-1).id');action(page,'3d-fit');return ev(page,'plateId')
def screen(page,point):return ev(page,"p=>{const q=conduit.model3d.camera.project(p),r=conduit.model3d.host.getBoundingClientRect();return {x:r.x+q.x,y:r.y+q.y}}",point)
def export_pair(page,fixture):
 for fmt,suffix in [('dxf','ascii'),('dxf-binary','binary')]:
  with page.expect_download() as download:page.evaluate('fmt=>conduit.doExport(fmt)',fmt)
  target=OUT/f'visual3d-{BACKEND}-{fixture}-{suffix}.dxf';download.value.save_as(str(target))
  ok(f'{BACKEND} {fixture} {suffix} is an actual browser DXF download',target.stat().st_size>100)
def drag_plane(page,name,du,dv):
 data=ev(page,"({name,du,dv})=>{const h=conduit.model3d.visual.hitHandles.find(h=>h.id===name),c=conduit.model3d.camera,r=conduit.model3d.host.getBoundingClientRect(),a=c.project(h.point),q=c.project({x:h.point.x+h.u.x*du+h.v.x*dv,y:h.point.y+h.u.y*du+h.v.y*dv,z:h.point.z+h.u.z*du+h.v.z*dv});return {x:r.x+h.x,y:r.y+h.y,dx:q.x-a.x,dy:q.y-a.y}}",{'name':name,'du':du,'dv':dv})
 page.mouse.move(data['x'],data['y']);page.mouse.down();page.mouse.move(data['x']+data['dx'],data['y']+data['dy'],steps=5);page.mouse.up();wait(page,70)
def drag_angle(page,name,delta):
 data=ev(page,"({name,delta})=>{const h=conduit.model3d.visual.hitHandles.find(h=>h.id===name),c=conduit.model3d.camera,r=conduit.model3d.host.getBoundingClientRect(),a=c.project(h.point),t=(h.value+delta)*Math.PI/180,q=c.project({x:h.origin.x+h.radius*(h.u.x*Math.cos(t)+h.v.x*Math.sin(t)),y:h.origin.y+h.radius*(h.u.y*Math.cos(t)+h.v.y*Math.sin(t)),z:h.origin.z+h.radius*(h.u.z*Math.cos(t)+h.v.z*Math.sin(t))});return {x:r.x+h.x,y:r.y+h.y,dx:q.x-a.x,dy:q.y-a.y}}",{'name':name,'delta':delta})
 page.mouse.move(data['x'],data['y']);page.mouse.down();page.mouse.move(data['x']+data['dx'],data['y']+data['dy'],steps=8);page.mouse.up();wait(page,70)
def drag(page,name,delta):
 data=ev(page,"({name,delta})=>{const v=conduit.model3d.visual,h=v.hitHandles.find(h=>h.id===name),r=conduit.model3d.host.getBoundingClientRect(),a=conduit.model3d.camera.project(h.point),q=conduit.model3d.camera.project({x:h.point.x+h.axis.x*delta,y:h.point.y+h.axis.y*delta,z:h.point.z+h.axis.z*delta});return {x:r.x+h.x,y:r.y+h.y,dx:q.x-a.x,dy:q.y-a.y,old:v.session.value(h.field)}}",{'name':name,'delta':delta})
 page.mouse.move(data['x'],data['y']);page.mouse.down();page.mouse.move(data['x']+data['dx'],data['y']+data['dy'],steps=5);page.mouse.up();wait(page,70);return data
try:
 with sync_playwright() as p:
  browser=launch(p);context=browser.new_context(viewport={'width':1440,'height':1000},accept_downloads=True);page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)));h.load(page,BACKEND);blank(page)
  ok('requested '+BACKEND+' backend executes without substitution',ev(page,'conduit.model3d.renderer.backend').lower().startswith(BACKEND))
  ok('visual authoring is default without test preference override',ev(page,"conduit.options.modelingInteraction===undefined"))
  action(page,'3d-tools');ok('Create opens a searchable nonmodal palette',page.locator('.visual3d-palette').is_visible() and page.locator('.modal').count()==0)
  ok('all 22 tools appear in palette',page.locator('[data-visual-command^="create:"]').count()==22)
  page.locator('.visual3d-search input').fill('nothing matches');ok('search has explicit empty state',page.locator('.visual3d-empty').is_visible())
  page.locator('.visual3d-search input').fill('box');page.locator('[data-visual-command="create:box"]').click();ready(page)
  ok('box starts geometry preview without a dialog',ev(page,'!!conduit.model3d.previewDocument&&!conduit.modal'))
  ok('preview leaves source entities and history untouched',ev(page,'conduit.doc.entities.length===0&&conduit.history.undoStack.length===0'))
  ev(page,'window.previewIdentity=conduit.model3d.visual.session.resultId;window.preCamera=JSON.stringify(conduit.model3d.camera.snapshot())')
  field(page,'width',110);ok('inline dimension edits real preview geometry',ev(page,'conduit.model3d.visual.session.preview.entities.at(-1).feature3d.parameters.width==="110"'))
  drag(page,'width',20);ok('width dragging uses world-space distance',abs(ev(page,'conduit.model3d.visual.session.value("width")')-130)<.0001)
  ok('drag retains preview identity and working camera',ev(page,'conduit.model3d.visual.session.resultId===previewIdentity&&JSON.stringify(conduit.model3d.camera.snapshot())===preCamera'))
  ok('pointer samples create no model history entries',ev(page,'conduit.history.undoStack.length===0&&conduit.doc.entities.length===0'))
  page.locator('[data-visual-command=undo]').click();wait(page,55);ok('draft undo reverts just the last drag',ev(page,'conduit.model3d.visual.session.value("width")===110&&conduit.doc.entities.length===0'))
  page.locator('[data-visual-command=apply]').focus();page.keyboard.press('Control+Shift+z');wait(page,55);ok('draft keyboard redo restores the drag',ev(page,'conduit.model3d.visual.session.value("width")===130'))
  handle=page.locator('[data-visual-handle=height]');handle.focus();page.keyboard.press('ArrowUp');wait(page,55)
  ok('keyboard slider changes the shared parameter',ev(page,'conduit.model3d.visual.session.value("height")===46'))
  ok('handle exposes name and numeric slider value',handle.get_attribute('role')=='slider' and handle.get_attribute('aria-valuenow')=='46')
  field(page,'height',-2);ok('invalid geometry clears stale preview and disables Apply',ev(page,'!conduit.model3d.previewDocument') and page.locator('[data-visual-command=apply]').is_disabled() and page.locator('.visual3d-error').is_visible())
  field(page,'height',40);ok('corrected geometry enables Apply',page.locator('[data-visual-command=apply]').is_enabled())
  page.locator('[data-visual-field=width]').click();page.locator('.visual3d-entry input').fill('unknownVariable');ok('invalid expression gives inline feedback',page.locator('.visual3d-entry input').get_attribute('aria-invalid')=='true')
  ev(page,'conduit.model3d.visual.apply()');ok('invalid open field cannot commit an older valid value',ev(page,'conduit.model3d.visual.active&&conduit.doc.entities.length===0'))
  page.locator('.visual3d-entry input').fill('130');page.locator('.visual3d-entry input').press('Enter');apply(page)
  ok('Apply makes one native feature and one history entry',ev(page,'conduit.doc.entities.length===1&&conduit.doc.entities[0].feature3d.parameters.width==="130"&&conduit.history.undoStack.length===1'))
  action(page,'3d-undo');ok('model undo removes entire operation',ev(page,'conduit.doc.entities.length===0'));action(page,'3d-redo');ok('redo restores entire operation',ev(page,'conduit.doc.entities.length===1'))
  ev(page,'conduit.selection=new Set([conduit.doc.entities[0].id]);conduit.updateSelection();window.hist=conduit.history.undoStack.length');action(page,'3d-edit');ready(page);apply(page)
  ok('unchanged existing edit does not add history',ev(page,'conduit.history.undoStack.length===hist'))
  ev(page,"conduit.doc.parameters.Span=150;conduit.doc.entities[0].feature3d.parameters.width='Span';conduit.touch();conduit.model3d.sync()")
  action(page,'3d-edit');ready(page);drag(page,'width',12);ok('drag retains named parameter expressions',ev(page,"conduit.model3d.visual.session.parameters.width.includes('Span')&&conduit.model3d.visual.session.value('width')===162"));apply(page)
  ok('committed feature remains expression driven',ev(page,"conduit.doc.entities[0].feature3d.parameters.width.includes('Span')"))
  action(page,'3d-edit');ready(page);ev(page,'window.before=JSON.stringify(conduit.doc);window.hist=conduit.history.undoStack.length');field(page,'width',175);cancel(page)
  ok('Cancel changes neither geometry nor history',ev(page,'JSON.stringify(conduit.doc)===before&&conduit.history.undoStack.length===hist'))
  action(page,'3d-op-sphere');ready(page);ev(page,"(()=>{const v=conduit.model3d.visual;window.evaluations=v.session.evaluations;for(let i=0;i<20;i++){v.session.set('radius',20+i);v.requestPreview();}})()")
  # Wait for the actual coalesced frame; software GPU presentation is not a 120 ms deadline.
  page.wait_for_function('conduit.model3d.visual.frame===0',timeout=15000)
  ok('queued changes coalesce to one final geometry evaluation',ev(page,'conduit.model3d.visual.session.evaluations===evaluations+1&&conduit.model3d.visual.session.value("radius")===39'));cancel(page)
  action(page,'3d-op-box');ready(page);ev(page,"conduit.doc.parameters.ExternalChange=99;window.before=JSON.stringify(conduit.doc)");ev(page,'conduit.model3d.visual.apply()')
  ok('stale-source guard catches unversioned external mutations',ev(page,'JSON.stringify(conduit.doc)===before') and 'changed' in page.locator('.visual3d-error').inner_text());cancel(page)
  action(page,'3d-op-box');ready(page);ev(page,"conduit.edit('Independent edit',()=>conduit.doc.name='Independent edit')");ok('independent transaction cancels active draft',ev(page,'!conduit.model3d.visual.active&&!conduit.model3d.previewDocument'))
  blank(page);create_box(page);action(page,'3d-pick:face');action(page,'3d-view-top');ev(page,'conduit.selection.clear();conduit.updateSelection()')
  pt=screen(page,{'x':50,'y':40,'z':40});page.mouse.click(pt['x'],pt['y']);wait(page,40);ok('canvas face selection finds native top face',ev(page,'conduit.model3d.hit?.face===1'))
  page.locator('.model3d-context [data-action="3d-op-hole"]').click();ready(page);ok('contextual hole opens visual placement without modal',ev(page,'conduit.model3d.visual.session.kind==="hole"&&!conduit.modal'))
  ok('hole center has face-plane manipulator',ev(page,'conduit.model3d.visual.handles.some(h=>h.kind==="plane")'))
  ev(page,'window.uv0={u:conduit.model3d.visual.session.value("u"),v:conduit.model3d.visual.session.value("v")}')
  drag_plane(page,'face-position',10,5)
  ok('plane handle moves the hole center in local U/V coordinates',ev(page,'conduit.model3d.visual.session.value("u")===Math.round(uv0.u+10)&&conduit.model3d.visual.session.value("v")===Math.round(uv0.v+5)'))
  field(page,'diameter',10);option(page,'through',0);field(page,'depth',12);ok('blind depth has a draggable dimension',ev(page,'conduit.model3d.visual.handles.some(h=>h.field==="depth")'))
  option(page,'holeType',1);option(page,'counterDiameter',18);option(page,'counterDepth',4);page.locator('[data-visual-command=options-close]').click()
  ok('counterbore controls drive same valid preview',ev(page,'!!conduit.model3d.visual.session.preview&&conduit.model3d.visual.handles.some(h=>h.field==="counterDepth")'));apply(page)
  ok('visual hole preserves native feature dependencies',ev(page,'conduit.doc.entities.at(-1).feature3d.kind==="hole"&&conduit.doc.entities.at(-1).feature3d.inputs[0]===plateId'))
  export_pair(page,'counterbore')
  action(page,'3d-vertex');wait(page,80);ok('vertex edit demands explicit feature detach',page.locator('[data-visual-command=apply]').is_disabled())
  option(page,'detach',1);field(page,'z',45);ok('vertex preview does not detach live feature',ev(page,'!!conduit.doc.entities.at(-1).feature3d&&!!conduit.model3d.visual.session.preview'));cancel(page)
  blank(page);create_box(page);ev(page,'conduit.selection.clear();conduit.updateSelection()');action(page,'3d-op-transform');ok('missing selection opens canvas source picker',ev(page,'conduit.model3d.visual.picking===0'))
  pt=screen(page,{'x':50,'y':40,'z':40});page.mouse.click(pt['x'],pt['y']);ready(page);ok('canvas picker attaches original source identity',ev(page,'conduit.model3d.visual.session.inputs[0]===plateId'))
  ok('transform pivot defaults to selected stock center',ev(page,'conduit.model3d.visual.session.value("px")===50&&conduit.model3d.visual.session.value("py")===40&&conduit.model3d.visual.session.value("pz")===20'))
  drag(page,'dx',15);ok('translation axis edits displacement',ev(page,'conduit.model3d.visual.session.value("dx")===15'))
  page.locator('[data-visual-command="mode:rotate"]').click();ok('Rotate shows three oriented rings',ev(page,'conduit.model3d.visual.handles.length===3&&conduit.model3d.visual.handles.every(h=>h.kind==="angle")'))
  drag_angle(page,'rz',30);ok('rotation ring changes the angle through real pointer motion',abs(ev(page,'conduit.model3d.visual.session.value("rz")')-30)<1e-6)
  field(page,'rz',90);page.locator('[data-visual-command="mode:scale"]').click();field(page,'sx',1.2);ok('scale axes follow object rotation',ev(page,'Math.abs(conduit.model3d.visual.handles.find(h=>h.field==="sx").axis.y-1)<1e-8'));apply(page)
  ok('transform commits dependency based geometry',ev(page,'conduit.doc.entities.at(-1).feature3d.kind==="transform"&&conduit.doc.entities.at(-1).feature3d.parameters.rz==="90"'))
  export_pair(page,'transform')
  blank(page);action(page,'3d-sketch');ready(page)
  for n,v in [('width',70),('height',50),('x',0),('y',0)]:field(page,n,v)
  apply(page);ok('on-canvas sketch creates native DXF profile',ev(page,'conduit.doc.entities.at(-1).type==="LWPOLYLINE"'))
  action(page,'3d-op-extrude');ready(page);option(page,'extent',1);page.locator('[data-visual-command=options-close]').click();field(page,'height',50)
  ok('symmetric extrusion handle represents total length',ev(page,'conduit.model3d.visual.handles.find(h=>h.field==="height").factor===2'))
  option(page,'extent',2);page.locator('[data-visual-command=options-close]').click();ok('two-sided extrusion exposes both handles',ev(page,'conduit.model3d.visual.handles.some(h=>h.field==="distance2")'));field(page,'distance2',15);apply(page)
  ok('extrusion retains native source profile',ev(page,'conduit.doc.entities.length===2&&conduit.doc.entities[1].feature3d.kind==="extrude"'))
  export_pair(page,'extrusion')
  action(page,'3d-edit');ready(page);field(page,'height',60);page.locator('[data-visual-command=options]').click();page.locator('[data-visual-command=advanced]').click()
  ok('optional Advanced handoff retains draft fields',page.locator('[data-model-field=height]').input_value()=='60' and ev(page,'!conduit.model3d.visual.active'))
  ev(page,'conduit.closeModal()');action(page,'3d-op-box');ready(page)
  ev(page,'window.styleBefore=conduit.model3d.renderer.style;window.geometryBefore=JSON.stringify(conduit.doc)')
  for style in ['shaded','shaded-edges','shaded-hidden','wireframe','hidden','wireframe-hidden','realistic','realistic-edges','conceptual','gray','sketchy','xray','flat','flat-edges','clay','normals']:
   ev(page,'style=>{conduit.model3d.renderer.style=style;conduit.model3d.renderer.draw()}',style)
   ok(BACKEND+' visual manipulation remains active in '+style,ev(page,'conduit.model3d.visual.active&&!!conduit.model3d.visual.session.preview&&JSON.stringify(conduit.doc)===geometryBefore&&conduit.model3d.visual.hitHandles.length>0'))
  ev(page,'conduit.model3d.renderer.style=styleBefore');page.screenshot(path=str(OUT/f'visual3d-{BACKEND}-desktop.png'))
  action(page,'mode-draw')
  ok('return to 2D cancels draft without creating geometry',ev(page,'!conduit.model3d.visual.active&&!conduit.model3d.previewDocument&&conduit.doc.entities.length===2'))
  action(page,'mode-3d');action(page,'3d-op-box');ready(page);ev(page,"async()=>{await conduit.newDocument('blank')}");ok('document switch releases isolated draft',ev(page,'!conduit.model3d.visual.active'));context.close()
  for width,height in [(320,568),(390,844),(844,390),(820,1180),(1024,768)]:
   context=browser.new_context(viewport={'width':width,'height':height},has_touch=True,is_mobile=True,device_scale_factor=1);page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)));h.load(page,BACKEND);blank(page);action(page,'3d-tools');prefix=f'{width}x{height}'
   ok(prefix+' palette bounded',bounded(page,'.visual3d-palette'));ok(prefix+' no autofocus keyboard on open',ev(page,'document.activeElement.tagName!=="INPUT"'))
   page.locator('[data-visual-command="create:box"]').click();ready(page);ok(prefix+' canvas keeps useful height',ev(page,'conduit.model3d.camera.pixelHeight>180'))
   ok(prefix+' controls and confirmation bounded',bounded(page,'.visual3d-controls') and bounded(page,'[data-visual-command=apply]') and bounded(page,'[data-visual-command=cancel]'))
   ok(prefix+' handles keep 44px targets',page.locator('[data-visual-handle]').evaluate_all('els=>els.length>0&&els.every(e=>e.getBoundingClientRect().width>=44&&e.getBoundingClientRect().height>=44)'))
   ok(prefix+' old dock does not cover editing controls',page.locator('.model3d-dock').is_hidden());page.locator('[data-visual-command=options]').click()
   ok(prefix+' options nonmodal and bounded',bounded(page,'.visual3d-options') and not ev(page,'!!conduit.modal'));ok(prefix+' readable numeric options',page.locator('[data-visual-option=width]').evaluate('e=>parseFloat(getComputedStyle(e).fontSize)>=16'))
   page.locator('[data-visual-command=options-close]').click();field(page,'width',125);ok(prefix+' inline edit does not scroll page',ev(page,'scrollX===0&&scrollY===0&&conduit.model3d.visual.session.value("width")===125'))
   page.locator('[data-visual-field=height]').click();ok(prefix+' exact field bounded',bounded(page,'.visual3d-entry'));page.locator('.visual3d-entry input').press('Escape');ok(prefix+' Escape closes just exact field first',ev(page,'conduit.model3d.visual.active&&conduit.model3d.visual.entryField===null'))
   ok(prefix+' dimension badges cannot intercept handle targets',page.evaluate('''()=>{const handles=[...document.querySelectorAll('[data-visual-handle]')].filter(e=>!e.closest('[hidden]')).map(e=>e.getBoundingClientRect());return [...document.querySelectorAll('.visual3d-dimension')].filter(e=>!e.closest('[hidden]')).every(e=>{const r=e.getBoundingClientRect();return handles.every(h=>!(r.left<h.right&&r.right>h.left&&r.top<h.bottom&&r.bottom>h.top))})}'''))
   ev(page,"conduit.iconography.setMode('labels')")
   ok(prefix+' explicit label preference is honored',page.locator('[data-visual-command=options]>span').evaluate('e=>getComputedStyle(e).display!=="none"'))
   ok(prefix+' labels never push Apply outside viewport',bounded(page,'[data-visual-command=apply]'))
   ev(page,"conduit.iconography.setMode('auto')")
   page.screenshot(path=str(OUT/f'visual3d-{BACKEND}-{width}-workspace.png'))
   if width==390:
    page.locator('[data-visual-field=height]').click()
    ev(page,"Object.defineProperty(visualViewport,'height',{configurable:true,value:460});visualViewport.dispatchEvent(new Event('resize'))");wait(page,90)
    ok('keyboard viewport reduces chrome and keeps exact input reachable',page.locator('.app').evaluate('e=>e.classList.contains("workspace-keyboard")') and page.locator('.visual3d-entry').evaluate('e=>e.getBoundingClientRect().bottom<=460'))
    ok('keyboard viewport retains visible Apply and Cancel',page.locator('[data-visual-command=apply]').evaluate('e=>e.getBoundingClientRect().bottom<=460&&e.getBoundingClientRect().height>=44'))
    page.screenshot(path=str(OUT/f'visual3d-{BACKEND}-keyboard.png'))
    page.locator('.visual3d-entry input').press('Escape');ev(page,"delete visualViewport.height;visualViewport.dispatchEvent(new Event('resize'))");wait(page,90)
    ok('closing inline input returns focus to canvas',page.locator('.viewport3d').evaluate('e=>e===document.activeElement'))
    ev(page,'window.before=JSON.stringify(conduit.doc);window.start=conduit.model3d.visual.session.snapshot()')
    target=ev(page,"()=>{const h=conduit.model3d.visual.hitHandles.find(h=>h.id==='width'),r=conduit.model3d.host.getBoundingClientRect();return {x:r.x+h.x,y:r.y+h.y}}")
    cdp=context.new_cdp_session(page);pt={'x':target['x'],'y':target['y'],'id':1};cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[pt]});pt['y']-=28;cdp.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[pt]});wait(page,55)
    ok('one finger begins a real handle gesture',ev(page,'!!conduit.model3d.visual.drag'));second={'x':max(35,target['x']-80),'y':target['y']+45,'id':2}
    cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[pt,second]});wait(page,50);ok('second finger rolls back incomplete handle gesture',ev(page,'!conduit.model3d.visual.drag&&JSON.stringify(conduit.model3d.visual.session.snapshot())===JSON.stringify(start)'))
    second['y']+=15;cdp.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[pt,second]});cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[pt]});cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]});wait(page,80)
    ok('pinch and trailing touch do not commit geometry',ev(page,'JSON.stringify(conduit.doc)===before&&conduit.doc.entities.length===0'))
   apply(page);ok(prefix+' touch Apply makes one feature and transaction',ev(page,'conduit.doc.entities.length===1&&conduit.history.undoStack.length===1'));context.close()
  browser.close()
 ok('no uncaught errors in visual authoring',not errors)
finally:
 h.close();(OUT/f'visual3d-browser-{BACKEND}.json').write_text(json.dumps({'checks':checks,'errors':errors,'passed':len(checks),'origin':'localhost' if NATIVE else 'opaque origin with explicit memory storage','physicalDevice':False,'requestedBackend':BACKEND,'nativeStorage':NATIVE},indent=2))
print(f'Visual 3D browser assertions: {len(checks)}')
