"""Actual editor controls, native downloads and gradient pixels (standalone by default)."""
import functools, http.server, json, os, shutil, threading
from pathlib import Path
from playwright.sync_api import sync_playwright
import ezdxf
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'artifacts';OUT.mkdir(exist_ok=True)
checks=[];errors=[]
def ok(name,value):
    assert value,name
    checks.append({'name':name,'passed':True})
class Handler(http.server.SimpleHTTPRequestHandler):
    def log_message(self,*args):pass
server=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(Handler,directory=str(ROOT/'dist')))
threading.Thread(target=server.serve_forever,daemon=True).start()
def boot(page):
    if os.environ.get('CONDUIT_TEST_ORIGIN')=='localhost':page.goto(f'http://127.0.0.1:{server.server_port}/?fresh=1&renderer=canvas')
    else:page.set_content((ROOT/'dist/ConduitCAD.html').read_text().replace("mountWorkbench(document.getElementById('app'))","mountWorkbench(document.getElementById('app'),{backend:'canvas'})"))
    page.wait_for_function('document.documentElement.dataset.ready === "true"')
    page.evaluate('conduit.store.save=async()=>{};conduit.store.schedule=()=>{};conduit.doc.entities=[];conduit.doc.blocks={};conduit.history.clear();conduit.renderer.setDocument(conduit.doc);conduit.updateUI()')
try:
  with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_EXECUTABLE') or shutil.which('chromium'),headless=True,args=['--no-sandbox'])
    context=browser.new_context(viewport={'width':1440,'height':1000},accept_downloads=True)
    page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)));boot(page)
    page.evaluate("conduit.doc.entities=[{id:'source',type:'LINE',layer:'0',a:{x:0,y:0},b:{x:100,y:0}}];conduit.selection=new Set(['source']);conduit.touch();conduit.updateUI()")
    page.locator('[data-action="dimension-source"]').click()
    ok('selected line creates a managed associated dimension',page.evaluate("conduit.selected()[0].dimension.references.b.entityId==='source'"))
    page.locator('[data-dim="offset"]').fill('50');page.locator('[data-dim="offset"]').press('Tab')
    ok('dimension offset inspector updates picture immediately',page.evaluate('conduit.selected()[0].definitionPoint.y===50'))
    page.locator('[data-dim="text"]').fill('Length <> mm');page.locator('[data-dim="text"]').press('Tab')
    ok('dimension text override is editable',page.evaluate("conduit.selected()[0].text==='Length <> mm'"))
    page.locator('[data-dim="dimtxt"]').fill('-1');page.locator('[data-dim="dimtxt"]').press('Tab')
    ok('invalid dimension numeric edit rolls back',float(page.locator('[data-dim="dimtxt"]').input_value())>0)
    page.evaluate("conduit.edit('Change source',()=>{conduit.doc.entities[0].b.x=180})")
    ok('source geometry change regenerates measurement',page.evaluate('conduit.selected()[0].measurement===180'))
    page.evaluate('conduit.history.undo()');ok('undo restores associated dimension and source together',page.evaluate('conduit.selected()[0].measurement===100 && conduit.doc.entities[0].b.x===100'))
    page.evaluate('conduit.history.redo();conduit.renderer.fit();conduit.gridSnap=false;conduit.objectSnap=false')
    page.wait_for_timeout(100)
    grip=page.evaluate("()=>{const w=conduit,g=w.grips(w.selected()[0]).find(g=>g.key==='dim:textMidpoint'),s=w.camera.screen(g),r=w.$('.viewport').getBoundingClientRect();return {x:s.x+r.left,y:s.y+r.top};}")
    page.mouse.move(grip['x'],grip['y']);page.mouse.down();page.mouse.move(grip['x']+30,grip['y']-40,steps=8);page.mouse.up()
    ok('mouse text grip sets manual text placement',page.evaluate('!!conduit.selected()[0].dimension.manualText'))
    page.locator('[data-action="dimension-reset-text"]').click();ok('reset restores automatic text placement',page.evaluate('!conduit.selected()[0].dimension.manualText'))
    with page.expect_download() as info:page.evaluate("conduit.doExport('dxf-binary')")
    path=OUT/'editing-browser-dimensions.dxf';info.value.save_as(str(path));d=ezdxf.readfile(path);audit=d.audit();dims=list(d.modelspace().query('DIMENSION'))
    ok('edited dimension binary download independently audits',not audit.errors and not audit.fixes and len(dims)==1)
    ok('native DSTYLE carries updated dimension overrides',dims[0].override()['dimtxt']>0)
    page.evaluate("conduit.action('dynamic-demo')")
    ok('dynamic sample exposes length and visibility controls',page.locator('[data-dynamic="Length"]').count()==1 and page.locator('[data-dynamic="Centerline"]').count()==1)
    page.locator('[data-dynamic="Length"]').fill('180');page.locator('[data-dynamic="Length"]').press('Tab')
    ok('dynamic inspector edits instance independently',page.evaluate('conduit.selected()[0].dynamicParameters.Length===180'))
    page.locator('[data-dynamic="Centerline"]').select_option('"Hidden"');page.wait_for_timeout(60)
    ok('visibility state removes centerline from evaluated scene',page.evaluate("conduit.renderer.scene.spans.get(conduit.selected()[0].id).pathCount===1"))
    page.evaluate('conduit.history.undo()');ok('dynamic visibility is undoable',page.evaluate("conduit.selected()[0].dynamicParameters.Centerline==='Shown'"))
    page.evaluate('conduit.renderer.fit()');page.wait_for_timeout(100)
    grip=page.evaluate("()=>{const w=conduit,g=w.grips(w.selected()[0]).find(g=>g.key==='dyn:Length'),s=w.camera.screen(g),r=w.$('.viewport').getBoundingClientRect();return {x:s.x+r.left,y:s.y+r.top};}")
    page.mouse.move(grip['x'],grip['y']);page.mouse.down();page.mouse.move(grip['x']+50,grip['y'],steps=8);page.mouse.up()
    ok('dynamic linear grip updates block parameter',page.evaluate('conduit.selected()[0].dynamicParameters.Length>180'))
    with page.expect_download() as info:page.evaluate("conduit.doExport('dxf-binary')")
    path=OUT/'editing-browser-dynamic.dxf';info.value.save_as(str(path));d=ezdxf.readfile(path);audit=d.audit();ins=list(d.modelspace().query('INSERT'))
    ok('dynamic binary download contains an evaluated native anonymous block',not audit.errors and not audit.fixes and ins[0].dxf.name.startswith('*UCC'))
    # Actual RGBA samples: rotated/sheared descriptors use the same Canvas/SVG affine basis.
    page.evaluate('''()=>{const w=conduit;w.selection.clear();w.cursor=null;w.doc.entities=[{id:'gradient',type:'HATCH',layer:'0',solid:true,loops:[{points:[{x:0,y:0},{x:100,y:0},{x:100,y:100},{x:0,y:100}]},{points:[{x:40,y:40},{x:60,y:40},{x:60,y:60},{x:40,y:60}]}],gradient:[[450,1],[451,0],[460,0],[461,0],[452,0],[462,0],[453,2],[463,0],[421,16711680],[463,1],[421,255],[470,'LINEAR']]}];w.camera.x=50;w.camera.y=50;w.camera.scale=4;w.renderer.grid=false;w.renderer.setDocument(w.doc);}''');page.wait_for_timeout(100)
    samples=page.evaluate('''()=>{const r=conduit.renderer;return [10,90,50].map(x=>{const p=r.camera.screen({x,y:50});return [...r.ctx.getImageData(Math.round(p.x*r.dpr),Math.round(p.y*r.dpr),1,1).data]})}''')
    ok('LINEAR gradient displays distinct native color endpoints',samples[0][0]>210 and samples[0][2]<45 and samples[1][2]>210 and samples[1][0]<45)
    ok('gradient hatch island remains transparent',samples[2][3]==0)
    page.screenshot(path=str(OUT/'editing-linear-gradient.png'))
    with page.expect_download() as info:page.evaluate("conduit.doExport('svg')")
    path=OUT/'editing-gradient.svg';info.value.save_as(str(path));ok('SVG uses a real linearGradient rather than flat-color fill','<linearGradient' in path.read_text())
    page.evaluate("()=>{const w=conduit,h=structuredClone(w.doc.entities[0]);w.doc.blocks.Gradient={name:'Gradient',entities:[h]};w.doc.entities=[{id:'gblock',type:'INSERT',layer:'0',block:'Gradient',x:200,y:200,sx:2,sy:.5,rotation:35}];w.renderer.setDocument(w.doc);w.renderer.fit();}")
    page.wait_for_timeout(100)
    samples=page.evaluate("()=>{const r=conduit.renderer,g=r.scene.paths[0].gradient,m=g.frame;return [10,90,50].map(x=>{const p=r.camera.screen({x:m[0]*x+m[2]*50+m[4],y:m[1]*x+m[3]*50+m[5]});return [...r.ctx.getImageData(Math.round(p.x*r.dpr),Math.round(p.y*r.dpr),1,1).data]});}")
    ok('rotated nonuniform block transform preserves gradient direction',samples[0][0]>210 and samples[0][2]<45 and samples[1][2]>210 and samples[1][0]<45)
    ok('transformed gradient retains its island clip',samples[2][3]==0)
    context.close()
    mobile=browser.new_context(viewport={'width':390,'height':844},is_mobile=True,has_touch=True,device_scale_factor=2)
    page=mobile.new_page();page.on('pageerror',lambda e:errors.append(str(e)));boot(page);page.evaluate("conduit.action('dynamic-demo')")
    page.get_by_role('button',name='Edit',exact=True).tap();page.locator('[data-dynamic="Length"]').fill('220');page.locator('[data-dynamic="Length"]').press('Tab')
    ok('mobile property edit updates dynamic geometry',page.evaluate('conduit.selected()[0].dynamicParameters.Length===220'))
    ok('mobile inspector avoids horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    page.screenshot(path=str(OUT/'editing-mobile-properties.png'))
    ok('no uncaught browser exceptions',not errors)
    browser.close()
finally:server.shutdown();server.server_close()
report={'checks':checks,'passed':len(checks),'errors':errors,'backend':'Canvas 2D','physicalDevice':False,'origin':os.environ.get('CONDUIT_TEST_ORIGIN','standalone')}
(OUT/'browser-cad-editing.json').write_text(json.dumps(report,indent=2));print(json.dumps(report,indent=2))
