"""Real pointer drawing, native inspectors and DXF readback; Canvas/emulated touch."""
import functools, http.server, json, os, shutil, subprocess, threading
from pathlib import Path
from playwright.sync_api import sync_playwright
import ezdxf
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'artifacts'; OUT.mkdir(exist_ok=True)
checks, errors = [], []
cases = json.loads(subprocess.check_output(['node', '--input-type=module', '-e', "import {TOOL_CASES} from './tests/drawing-fixtures.mjs';console.log(JSON.stringify(TOOL_CASES))"], cwd=ROOT))
def ok(name, value):
    assert value, name
    checks.append({'name': name, 'passed': True}); print(name, flush=True)
class Handler(http.server.SimpleHTTPRequestHandler):
    def log_message(self, *args): pass
server = http.server.ThreadingHTTPServer(('127.0.0.1', 0), functools.partial(Handler, directory=str(ROOT / 'dist')))
threading.Thread(target=server.serve_forever, daemon=True).start()
try:
  with sync_playwright() as p:
    browser = p.chromium.launch(executable_path=os.environ.get('CHROMIUM_EXECUTABLE') or shutil.which('chromium'), headless=True, args=['--no-sandbox'])
    page = browser.new_page(viewport={'width':1440, 'height':1000}, accept_downloads=True, has_touch=True)
    page.set_default_timeout(8000)
    page.on('pageerror', lambda e: errors.append(str(e)))
    if os.environ.get('CONDUIT_TEST_ORIGIN')=='localhost':page.goto(f'http://127.0.0.1:{server.server_port}/?fresh=1&renderer=canvas')
    else:page.set_content((ROOT/'dist/ConduitCAD.html').read_text().replace("mountWorkbench(document.getElementById('app'))","mountWorkbench(document.getElementById('app'),{backend:'canvas'})"))
    page.wait_for_function('document.documentElement.dataset.ready === "true"')
    page.evaluate('''()=>{conduit.store.save=async()=>{};conduit.store.schedule=()=>{};conduit.doc.entities=[];conduit.doc.constraints=[];
      conduit.doc.parameters={};conduit.doc.activeLayout='Model';conduit.currentLayer='0';conduit.gridSnap=false;conduit.objectSnap=false;conduit.ortho=false;
      conduit.history.clear();conduit.selection.clear();conduit.touch();conduit.updateUI();conduit.camera.x=60;conduit.camera.y=30;conduit.camera.scale=1.8;conduit.renderer.invalidate();}''')
    def at(point):
      return page.evaluate('''p=>{const q=conduit.camera.screen(p),b=conduit.$('.viewport').getBoundingClientRect();return {x:q.x+b.x,y:q.y+b.y}}''', point)
    def click(point, touch=False):
      q=at(point)
      (page.touchscreen.tap if touch else page.mouse.click)(q['x'],q['y'])
    def palette(tool):
      page.evaluate('conduit.moreDialog(true)')
      page.locator(f'[data-tool="{tool}"]').last.click()
    page.evaluate('conduit.moreDialog(true)')
    page.locator('[data-drawing-search]').fill('ellipse')
    ok('search isolates ellipse tool choices',page.locator('[data-tool-search]:visible').count()==2)
    page.locator('[data-tool="ellipse"]').last.click()
    ok('palette closes and starts staged command',page.evaluate("!conduit.modal && conduit.tool==='ellipse' && conduit.drawingSession.points.length===0"))
    for tool,points,kind in cases:
      palette(tool)
      before=page.evaluate('conduit.doc.entities.length')
      for point in points: click(point)
      if page.evaluate('conduit.drawingSession.canFinish'):page.locator('.finish-button').click()
      ok(f'{tool}: pointer workflow creates one native {kind}',page.evaluate('(v)=>conduit.doc.entities.length===v[0]+1 && conduit.doc.entities.at(-1).type===v[1]',[before,kind]))
      ok(f'{tool}: repeat remains armed without stale draft',page.evaluate('(tool)=>conduit.tool===tool && !conduit.draft.length && !conduit.preview',tool))
    palette('arc')
    click({'x':0,'y':0}); click({'x':50,'y':0}); before=page.evaluate('conduit.doc.entities.length')
    click({'x':100,'y':0})
    ok('invalid collinear arc keeps first two picks',page.evaluate('(n)=>conduit.doc.entities.length===n && conduit.draft.length===2',before))
    page.locator('[data-action="draw-back"]').click()
    ok('Back removes exactly one staged pick',page.evaluate('conduit.draft.length===1'))
    page.locator('[data-action="draw-exact-point"]').click()
    page.locator('[data-field="point"]').fill('@50,50');page.locator('[data-action="modal-confirm"]').click()
    page.evaluate("conduit.executeCommand('NEXT @50,-50')")
    ok('relative exact point and NEXT complete the same session',page.evaluate('(n)=>conduit.doc.entities.length===n+1 && conduit.doc.entities.at(-1).type==="ARC"',before))
    palette('spline')
    for point in [{'x':0,'y':0},{'x':50,'y':50},{'x':100,'y':0}]:click(point)
    page.locator('[data-action="draw-close"]').click()
    ok('Close creates native closed spline and clears draft',page.evaluate('conduit.doc.entities.at(-1).closed && conduit.draft.length===0'))
    palette('polygon');page.locator('[data-action="draw-options"]').click()
    page.locator('[name="sides"]').fill('8');page.locator('[name="circumscribed"]').select_option('true');page.locator('[data-action="modal-confirm"]').click()
    start,end=at({'x':0,'y':0}),at({'x':40,'y':0})
    page.mouse.move(**start);page.mouse.down();page.mouse.move(**end,steps=4)
    ok('drag shows native polygon preview',page.evaluate("conduit.preview?.type==='LWPOLYLINE'&&conduit.preview.points.length===8"))
    page.mouse.up()
    ok('drag commits configured polygon exactly once',page.evaluate('conduit.doc.entities.at(-1).points.length===8'))
    page.evaluate("conduit.setTool('select');conduit.history.undo();conduit.history.redo()")
    ok('new drawing transaction supports undo redo',page.evaluate('conduit.doc.entities.at(-1).points.length===8'))
    palette('mtext');page.locator('[data-action="draw-options"]').click()
    page.locator('[name="text"]').fill('Equipment\nFlow = 42');page.locator('[name="height"]').fill('8');page.locator('[data-action="modal-confirm"]').click()
    click({'x':0,'y':80});click({'x':120,'y':0});page.evaluate("conduit.setTool('select')")
    ok('multiline options produce native paragraph content',page.evaluate("s=>conduit.doc.entities.at(-1).text===s", r"Equipment\PFlow = 42"))
    page.locator('[data-native-prop="mtextContent"]').fill('Revised\nNote');page.locator('[data-native-prop="mtextContent"]').press('Tab')
    ok('native MTEXT inspector keeps paragraph semantics',page.evaluate("s=>conduit.selected()[0].text===s", r"Revised\PNote"))
    page.evaluate("conduit.executeCommand('ELLIPSE 0,0 80,0 0,40');conduit.selectEntity(conduit.doc.entities.at(-1).id)")
    page.locator('[data-native-prop="ratio"]').fill('0.25');page.locator('[data-native-prop="ratio"]').press('Tab')
    ok('ellipse axis inspector changes native ratio',page.evaluate('conduit.selected()[0].ratio===.25'))
    page.locator('[data-native-prop="ratio"]').fill('2');page.locator('[data-native-prop="ratio"]').press('Tab')
    ok('invalid native property rolls back without corrupting entity',page.evaluate('conduit.selected()[0].ratio===.25'))
    page.evaluate("conduit.executeCommand('BEZIER 0,0 30,60 60,60 100,0');conduit.selectEntity(conduit.doc.entities.at(-1).id)")
    page.locator('[data-action="native-vertices"]').click();page.locator('[data-vertex="1"][data-axis="y"]').fill('75');page.locator('[data-action="modal-confirm"]').click()
    ok('control table edits spline without flattening',page.evaluate('conduit.selected()[0].controlPoints[1].y===75 && conduit.selected()[0].knots.length===8'))
    q1,q2=at({'x':30,'y':75}),at({'x':30,'y':100})
    page.mouse.move(**q1);page.mouse.down();page.mouse.move(**q2,steps=5);page.mouse.up()
    ok('spline control grip changes the native curve',page.evaluate('Math.abs(conduit.selected()[0].controlPoints[1].y-100)<1'))
    page.evaluate("conduit.executeCommand('CIRCLE 0,0 60');const a=conduit.doc.entities.at(-1).id;conduit.executeCommand('CIRCLE 0,0 20');conduit.selection=new Set([a,conduit.doc.entities.at(-1).id]);conduit.updateSelection();conduit.action('hatch-selection')")
    page.locator('[name="pattern"]').select_option('cross');page.locator('[data-action="modal-confirm"]').click()
    ok('selected circular boundaries keep native arcs and island topology',page.evaluate('conduit.selected()[0].type==="HATCH" && conduit.selected()[0].loops.length===2 && conduit.selected()[0].loops.every(l=>l.edges[0].type===2)'))
    page.evaluate("conduit.action('export')")
    with page.expect_download() as download:page.locator('[data-export="dxf-binary"]').click()
    file=OUT/'drawing-tools-browser.dxf';download.value.save_as(str(file));doc=ezdxf.readfile(file);audit=doc.audit()
    ok('all drawn tools save as a real independently audited binary DXF',not audit.errors and not audit.fixes)
    ok('binary download contains all fifteen native entity families',set(row[2] for row in cases)<=set(e.dxftype() for e in doc.modelspace()))
    page.evaluate('conduit.closeModal()')
    page.evaluate("conduit.doc.blocks.ToolPart={name:'ToolPart',base:{x:0,y:0},entities:[],ports:[]};conduit.doc.entities.push({id:'tool-insert',type:'INSERT',block:'ToolPart',x:0,y:0,sx:1,sy:1,layer:'0'});conduit.selectEntity('tool-insert')")
    page.locator('[data-action="block-edit"]').click()
    page.evaluate("conduit.executeCommand('ARC 0,0 40,40 80,0');conduit.executeCommand('POLYGON 5 0,0 20,0')")
    ok('new tools author native entities inside isolated block canvas',page.evaluate("conduit.blockSession && conduit.doc.entities.map(e=>e.type).join()==='ARC,LWPOLYLINE'"))
    page.locator('.block-editor-bar [data-action="block-save-close"]').click()
    ok('block save retains new entity types on shared references',page.evaluate("conduit.doc.blocks.ToolPart.entities[0].type==='ARC'&&conduit.selected()[0].type==='INSERT'"))
    # Mobile uses genuine touchscreen taps, not pointerType labels on mouse events.
    page.set_viewport_size({'width':390,'height':844});page.evaluate("conduit.closePanels();conduit.doc.entities=[];conduit.doc.constraints=[];conduit.doc.name='Native curve study';conduit.selection.clear();conduit.history.clear();conduit.touch();conduit.updateUI();conduit.camera.x=40;conduit.camera.y=30;conduit.camera.scale=1.5;conduit.renderer.invalidate()")
    page.locator('[data-action="shapes"]').click();page.locator('[data-drawing-search]').fill('arc')
    ok('mobile shape palette exposes searched native arc tool',page.locator('[data-tool="arc"]').last.is_visible())
    page.screenshot(path=str(OUT/'drawing-tools-mobile-palette.png'))
    page.locator('[data-tool="arc"]').last.click();before=page.evaluate('conduit.doc.entities.length')
    for point in [{'x':0,'y':0},{'x':40,'y':40},{'x':80,'y':0}]:click(point,True)
    ok('native touch taps draw a single arc on mobile',page.evaluate('(n)=>conduit.doc.entities.length===n+1&&conduit.doc.entities.at(-1).type==="ARC"',before))
    ok('mobile active command has 44px controls and no overflow',page.locator('[data-action="draw-exact-point"]').bounding_box()['height']>=44 and page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    palette('spline');click({'x':0,'y':0},True);click({'x':60,'y':30},True)
    page.locator('.toast').evaluate_all("(nodes)=>nodes.forEach(n=>n.style.display='none')")
    page.screenshot(path=str(OUT/'drawing-tools-mobile-command.png'))
    a=page.locator('.finish-button').bounding_box();b=page.locator('.drawing-session-controls').bounding_box()
    ok('Finish and touch command bar do not overlap',a['y']+a['height']<=b['y'] or b['y']+b['height']<=a['y'])
    page.locator('.finish-button').click()
    before=page.evaluate('conduit.doc.entities.length');palette('arc')
    # Send two real touch contacts together; gesture must not commit a point.
    cdp=page.context.new_cdp_session(page)
    for pts in [[{'x':130,'y':290,'id':1},{'x':240,'y':290,'id':2}],[{'x':110,'y':290,'id':1},{'x':260,'y':290,'id':2}]]:
      cdp.send('Input.dispatchTouchEvent',{'type':'touchStart' if pts[0]['x']==130 else 'touchMove','touchPoints':pts})
    cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]})
    ok('two-finger gesture creates neither entity nor accidental draft point',page.evaluate('(n)=>conduit.doc.entities.length===n&&!conduit.draft.length',before))
    page.locator('[data-action="draw-cancel"]').click()
    ok('Cancel returns to select without stale preview',page.evaluate("conduit.tool==='select'&&!conduit.drawingSession&&!conduit.preview"))
    ok('no uncaught browser exceptions',not errors)
    browser.close()
finally:
    server.shutdown();server.server_close()
    (OUT/'browser-drawing-tools.json').write_text(json.dumps({'checks':checks,'passed':len(checks),'errors':errors,'backend':'Canvas 2D','physicalDevice':False,'origin':os.environ.get('CONDUIT_TEST_ORIGIN','standalone'),'storage':'save/schedule stubbed for deterministic transactions'},indent=2)+'\n')
print(json.dumps({'passed':len(checks),'errors':errors},indent=2))
