import test from 'node:test';
import assert from 'node:assert/strict';
import { createDocument, entity, line, circle, polyline, text, clone, editDimension, regenerateDimensions, dynamicValues } from '@conduitcad/model';
import { PlanarEditSession, PLANAR_TYPES, PLANAR_OPERATIONS, planarEditable, fields2, editFields2, handles2, dragHandle2, expressionDelta2, number2 } from '@conduitcad/manipulation2d';
import { ConstraintSolver, evaluateExpression } from '@conduitcad/constraints';
import { History } from '@conduitcad/history';
import { writeDXF, writeDXFBinary, parseDXF } from '@conduitcad/dxf';
import { measurePoints3, sectionFrame3 } from '@conduitcad/manipulation3d';
import { V3, dot3, distance3 } from '@conduitcad/geometry3d';
const pt=(x,y)=>({x,y}),near=(a,b,e=1e-7)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
const fixture=e=>{const d=createDocument('Planar edit');d.entities=[e];return {d,e,s:new PlanarEditSession(d,[e.id])};};
const solve=(d)=>{const r=new ConstraintSolver().solve(d.entities,d.constraints,d.parameters);if(!r.converged)throw new Error('constraint conflict');regenerateDimensions(d);};
const rectangle=()=>entity('LWPOLYLINE',{closed:true,points:[pt(0,0),pt(100,0),pt(100,50),pt(0,50)],parametric:{kind:'rectangle',width:'100',height:'50'}});
const dynamicFixture=()=>{const d=createDocument();d.blocks.bar={name:'bar',base:pt(0,0),entities:[line(pt(0,0),pt(10,0),{id:'edge'})],ports:[],dynamic:{version:1,parameters:[{name:'Length',type:'distance',default:10,min:1,max:1000,grip:{base:pt(0,0),direction:pt(1,0)}}],actions:[{type:'stretch',parameter:'Length',entities:['edge'],direction:pt(1,0),box:{minX:9,minY:-1,maxX:11,maxY:1}}]}};const e=entity('INSERT',{block:'bar',x:50,y:20,rotation:90,sx:2,sy:2});d.entities=[e];return {d,e};};
test('native editor inventory and operation registry are immutable',()=>{assert.ok(Object.isFrozen(PLANAR_TYPES)&&Object.isFrozen(PLANAR_OPERATIONS));assert.equal(new Set(PLANAR_TYPES).size,21);assert.equal(PLANAR_OPERATIONS.length,6);});
for(const type of ['LINE','CIRCLE','ARC','ELLIPSE','POINT','RAY','XLINE','TEXT','MTEXT'])test(`native ${type} position is edited only in an isolated preview`,()=>{
 const e=entity(type,type==='LINE'?{a:pt(0,0),b:pt(100,0)}:type==='CIRCLE'||type==='ARC'?{c:pt(0,0),r:10,start:0,end:Math.PI}:type==='ELLIPSE'?{c:pt(0,0),major:pt(20,0),ratio:.5,start:0,end:Math.PI*2}:{p:pt(0,0),direction:pt(1,0),height:10,text:'Text',mtextWidth:30});
 const {d,s}=fixture(e),before=JSON.stringify(d);s.set('x','20+5');const preview=s.evaluate();assert.equal(JSON.stringify(d),before);assert.equal(s.evaluate(),preview);s.commit(d);near((d.entities[0].a||d.entities[0].c||d.entities[0].p).x,25);
});
test('exact field operation is atomic on invalid coupled geometry',()=>{const {d,e}=fixture(entity('ELLIPSE',{c:pt(0,0),major:pt(10,0),ratio:.5})),before=JSON.stringify(e);assert.throws(()=>editFields2(e,d,{x:20,minorRadius:30}),/Minor/);assert.equal(JSON.stringify(e),before);});
test('line length expression survives commit and later parameter changes',()=>{const {d,s}=fixture(line(pt(0,0),pt(10,0)));d.parameters.Width=100;const edit=new PlanarEditSession(d,[d.entities[0].id]);edit.set('length','Width/2');edit.commit(d);assert.equal(d.entities[0].parametric.length,'Width/2');near(d.entities[0].b.x,50);near(evaluateExpression(d.entities[0].parametric.length,{Width:200}),100);});
test('signed numeric and expression drags never accumulate nesting',()=>{near(+expressionDelta2('5',-10,5),-5);assert.equal(expressionDelta2('Width/2',10,50),'(Width/2) + 10');assert.equal(expressionDelta2('Width',0,80),'Width');assert.throws(()=>expressionDelta2('x',NaN,1));});
test('line endpoint drag updates actual length and angle, not a display polyline',()=>{const {d,s}=fixture(line(pt(0,0),pt(100,0)));s.evaluate();const h=handles2(s).find(h=>h.id==='end');dragHandle2(s,h,pt(0,100),s.snapshot());const e=s.evaluate().entities[0];near(e.b.x,100);near(e.b.y,100);near(s.value('angle'),45);assert.equal(d.entities[0].b.y,0);});
test('start grip keeps the opposite endpoint at its gesture-start position',()=>{const {s}=fixture(line(pt(0,0),pt(100,0)));s.set('length',150);s.evaluate();const h=handles2(s).find(h=>h.id==='start');dragHandle2(s,h,pt(10,20),s.snapshot());const e=s.evaluate().entities[0];near(e.a.x,10);near(e.a.y,20);near(e.b.x,150);near(e.b.y,0);});
test('line length grip follows orientation rather than world X',()=>{const {s}=fixture(line(pt(0,0),pt(0,100)));s.evaluate();dragHandle2(s,handles2(s).find(h=>h.id==='length'),pt(40,25),s.snapshot());near(s.value('length'),125);near(s.evaluate().entities[0].b.x,0);});
test('numeric zero-length and unsupported expressions never leave stale previews',()=>{const {s}=fixture(line(pt(0,0),pt(100,0)));s.evaluate();s.set('length','0');assert.equal(s.preview,null);assert.throws(()=>s.evaluate());s.set('length','unknown');assert.throws(()=>s.evaluate());s.set('length','50');near(s.evaluate().entities[0].b.x,50);});
test('circle radius drag preserves formula and creation identity',()=>{const d=createDocument();d.parameters.Size=40;const e=circle(pt(0,0),20,{parametric:{radius:'Size/2'}}),s=new PlanarEditSession(d,[],{create:e});s.evaluate();const before=s.snapshot(),h=handles2(s).find(h=>h.id==='radius');for(let i=1;i<=15;i++)dragHandle2(s,h,pt(i,0),before);assert.equal(s.parameters.radius,'(Size/2) + 15');near(s.evaluate().entities[0].r,35);s.commit(d);assert.equal(d.entities[0].id,e.id);});
test('arc angle grip and clockwise flags remain native',()=>{const {d,s}=fixture(entity('ARC',{c:pt(0,0),r:20,start:0,end:Math.PI/2,clockwise:true}));s.evaluate();dragHandle2(s,handles2(s).find(h=>h.id==='start'),pt(-20,20),s.snapshot());s.set('end',180);s.commit(d);near(d.entities[0].start,Math.PI/2);assert.equal(d.entities[0].clockwise,true);});
test('ellipse retains native major vector and parameter interval',()=>{const {d,s}=fixture(entity('ELLIPSE',{c:pt(10,20),major:pt(20,0),ratio:.5,start:.3,end:2.8}));s.set('majorRadius',40);s.set('minorRadius',15);s.set('angle',90);s.commit(d);near(d.entities[0].major.x,0);near(d.entities[0].major.y,40);near(d.entities[0].ratio,.375);near(d.entities[0].start,.3);});
test('rotated parametric rectangle size and origin are independently editable',()=>{const {d,s}=fixture(rectangle());s.set('angle',90);s.set('rectWidth',120);s.set('rectHeight',70);s.set('x',30);s.set('y',40);s.commit(d);const e=d.entities[0];near(e.points[1].x,30);near(e.points[1].y,160);near(e.points[2].x,-40);near(e.points[2].y,160);assert.equal(e.parametric.width,'120');});
for(const type of ['LWPOLYLINE','POLYLINE','LEADER','SOLID','TRACE','3DFACE'])test(`${type} control handles preserve native entity metadata`,()=>{const e=entity(type,{points:[pt(0,0),pt(30,0),pt(30,20)],flags:0,edgeFlags:5}),{d,s}=fixture(e);s.set('v1x',40);s.commit(d);assert.equal(d.entities[0].type,type);assert.equal(d.entities[0].edgeFlags,5);near(d.entities[0].points[1].x,40);});
test('triangular face duplicate fourth corner moves together',()=>{const e=entity('3DFACE',{points:[pt(0,0),pt(30,0),pt(30,20),pt(30,20)]}),{d,s}=fixture(e);assert.ok(!s.definitions.find(f=>f.name==='v3x'));s.set('v2y',40);s.commit(d);assert.deepEqual(d.entities[0].points[2],d.entities[0].points[3]);});
test('polyline bulge survives coordinate edits and is directly editable',()=>{const {d,s}=fixture(polyline([{x:0,y:0,bulge:1},pt(30,0),pt(30,20)],false));s.set('v0b','0.5');s.set('v2y',40);s.commit(d);near(d.entities[0].points[0].bulge,.5);near(d.entities[0].points[2].y,40);});
test('duplicate adjacent vertices are rejected atomically',()=>{const {d,s}=fixture(polyline([pt(0,0),pt(30,0),pt(30,20)],false));const before=JSON.stringify(d);s.set('v1x',0);assert.throws(()=>s.commit(d),/distinct/);assert.equal(JSON.stringify(d),before);});
test('rational spline edits retain degree knots and weights, discard stale fits',()=>{const e=entity('SPLINE',{controlPoints:[pt(0,0),pt(20,30),pt(40,0)],fitPoints:[pt(0,0),pt(40,0)],degree:2,knots:[0,0,0,1,1,1],weights:[1,.5,1]}),{d,s}=fixture(e);s.set('v1y',50);s.commit(d);assert.deepEqual(d.entities[0].weights,[1,.5,1]);assert.deepEqual(d.entities[0].knots,e.knots);assert.equal(d.entities[0].degree,2);assert.deepEqual(d.entities[0].fitPoints,[]);});
test('closed spline duplicate endpoint remains paired',()=>{const e=entity('SPLINE',{closed:true,controlPoints:[pt(0,0),pt(20,30),pt(40,0),pt(0,0)],degree:2,knots:[0,0,0,1,2,2,2]}),{d,s}=fixture(e);s.set('v0x',10);s.commit(d);near(d.entities[0].controlPoints.at(-1).x,10);});
test('native hatch loop editing preserves holes and pattern metadata',()=>{const e=entity('HATCH',{solid:true,loops:[{points:[pt(0,0),pt(100,0),pt(100,80),pt(0,80)]},{points:[pt(20,20),pt(30,20),pt(30,30),pt(20,30)]}],patternName:'SOLID'}),{d,s}=fixture(e);s.set('h0v1x',120);s.commit(d);assert.equal(d.entities[0].loops.length,2);near(d.entities[0].loops[0].points[1].x,120);});
test('crossing hatch outline fails without modifying original',()=>{const e=entity('HATCH',{solid:true,loops:[{points:[pt(0,0),pt(100,0),pt(100,80),pt(0,80)]}]}),{d,s}=fixture(e);s.set('h0v1x',50);s.set('h0v1y',100);assert.throws(()=>s.commit(d));near(d.entities[0].loops[0].points[1].x,100);});
test('MTEXT line editing retains width attachment and formatting codes',()=>{const {d,s}=fixture(entity('MTEXT',{p:pt(0,0),height:12,text:'a\\Pb',mtextWidth:90,attachment:2}));assert.equal(s.parameters.text,'a\nb');s.set('text','{\\C1;Red}\nSecond');s.set('mtextWidth',120);s.commit(d);assert.equal(d.entities[0].text,'{\\C1;Red}\\PSecond');assert.equal(d.entities[0].attachment,2);near(d.entities[0].mtextWidth,120);});
test('calculated text content is read-only, its position remains editable',()=>{const {d,s}=fixture(text(pt(0,0),'20',12,{calculation:{expression:'10*2'}}));assert.throws(()=>s.set('text','fake'),/read-only/);s.set('x',30);s.commit(d);assert.equal(d.entities[0].text,'20');});
for(const data of [
 {dimtype:32,a:pt(0,0),b:pt(80,50),definitionPoint:pt(0,70),dimensionAngle:0},
 {dimtype:33,a:pt(0,0),b:pt(80,60),offset:30},
 {dimtype:34,a:pt(0,0),b:pt(100,0),defpoint4:pt(0,0),definitionPoint:pt(0,100),defpoint5:pt(20,20)},
 {dimtype:35,definitionPoint:pt(-40,0),defpoint4:pt(40,0)},
 {dimtype:36,definitionPoint:pt(0,0),defpoint4:pt(40,0)},
 {dimtype:37,a:pt(100,0),b:pt(0,100),defpoint4:pt(0,0),definitionPoint:pt(20,20)},
 {dimtype:102,a:pt(80,50),b:pt(80,90),definitionPoint:pt(0,0)}
])test(`native dimension subtype ${data.dimtype&15} has real witness grips and regenerated pictures`,()=>{const d=createDocument(),e=entity('DIMENSION',data);editDimension(e,d);d.entities=[e];const s=new PlanarEditSession(d,[e.id],{process:regenerateDimensions});s.set('dimtxt',8);s.set('text','<> mm');s.evaluate();assert.ok(handles2(s).length>0);s.commit(d);assert.equal(d.entities[0].dimension.style.dimtxt,8);assert.equal(d.entities[0].text,'<> mm');});
test('rotated linear dimension uses its projected offset, not aligned distance',()=>{const d=createDocument(),e=entity('DIMENSION',{dimtype:32,a:pt(0,0),b:pt(80,50),definitionPoint:pt(0,70),dimensionAngle:0});editDimension(e,d);near(fields2(e,d).find(f=>f.name==='offset').value,70);});
test('dimension line offset keeps source associations; moving witness detaches only that reference',()=>{const d=createDocument(),a=line(pt(0,0),pt(100,0)),e=entity('DIMENSION',{dimtype:33,a:a.a,b:a.b,offset:20,dimension:{version:1,references:{a:{entityId:a.id,point:'a'},b:{entityId:a.id,point:'b'}}}});editDimension(e,d);d.entities=[a,e];let s=new PlanarEditSession(d,[e.id],{process:regenerateDimensions});s.set('offset',40);s.commit(d);assert.ok(d.entities[1].dimension.references.a);s=new PlanarEditSession(d,[e.id]);s.set('aX',-10);s.commit(d);assert.equal(d.entities[1].dimension.references.a,undefined);assert.ok(d.entities[1].dimension.references.b);});
test('editing a driven line updates the constraint rather than fighting it',()=>{const d=createDocument(),e=line(pt(0,0),pt(100,0));d.entities=[e];d.constraints=[{id:'length',type:'length',entityId:e.id,value:'100'}];const s=new PlanarEditSession(d,[e.id],{process:solve});s.set('length','150');const p=s.evaluate();assert.equal(d.constraints[0].value,'100');assert.equal(p.constraints[0].value,'150');near(Math.hypot(p.entities[0].b.x-p.entities[0].a.x,p.entities[0].b.y-p.entities[0].a.y),150);});
test('constraint expression chips solve actual geometry and reject conflict atomically',()=>{const d=createDocument(),e=line(pt(0,0),pt(100,0));d.entities=[e];d.constraints=[{id:'a',type:'length',entityId:e.id,value:'100'},{id:'b',type:'length',entityId:e.id,value:'100'}];const s=new PlanarEditSession(d,[e.id],{process:solve}),before=JSON.stringify(d);s.set('constraint:a','150');assert.throws(()=>s.commit(d),/conflict/);assert.equal(JSON.stringify(d),before);});
test('dynamic block numeric grips respect rotated nonuniform instance transform',()=>{const {d,e}=dynamicFixture(),s=new PlanarEditSession(d,[e.id]);s.evaluate();const h=handles2(s).find(h=>h.kind==='dynamic');dragHandle2(s,h,pt(0,20),s.snapshot());s.commit(d);near(d.entities[0].dynamicParameters.Length,20);});
test('dynamic grips use the current draft instance transform after rotation',()=>{const {d,e}=dynamicFixture(),s=new PlanarEditSession(d,[e.id]);s.set('rotation',0);s.evaluate();const h=handles2(s).find(h=>h.kind==='dynamic');dragHandle2(s,h,pt(20,0),s.snapshot());s.commit(d);near(d.entities[0].dynamicParameters.Length,20);});
for(const op of ['move','rotate','scale','offset'])test(`${op} previews from pristine input with copy and stable result IDs`,()=>{const d=createDocument(),e=line(pt(0,0),pt(100,0));d.entities=[e];const s=new PlanarEditSession(d,[e.id],{operation:op});s.set('copy',true);const k={move:'dx',rotate:'angle',scale:'factor',offset:'amount'}[op];s.set(k,op==='scale'?2:25);const a=s.evaluate(),id=s.resultIds[0];s.set(k,op==='scale'?3:35);s.evaluate();assert.equal(s.resultIds[0],id);assert.equal(d.entities.length,1);s.commit(d);assert.equal(d.entities.length,2);assert.deepEqual(d.entities[0],e);assert.equal(new Set(d.entities.map(e=>e.id)).size,2);});
test('uniform scaling updates supported parametric aliases',()=>{const {d,e}=fixture(circle(pt(0,0),20,{parametric:{radius:'Size/2'}}));d.parameters.Size=40;const s=new PlanarEditSession(d,[e.id],{operation:'scale'});s.set('factor','2');s.commit(d);near(d.entities[0].r,40);near(evaluateExpression(d.entities[0].parametric.radius,{Size:60}),60);});
test('offset preserves source and radius formula on native copied circle',()=>{const {d,e}=fixture(circle(pt(0,0),20,{parametric:{radius:'20'}}));const s=new PlanarEditSession(d,[e.id],{operation:'offset'});assert.equal(s.changed,true);s.commit(d);assert.equal(d.entities.length,2);near(d.entities[1].r,30);});
test('fillet operation produces a native ARC and two tangent line ends',()=>{const d=createDocument(),a=line(pt(0,0),pt(100,0)),b=line(pt(0,0),pt(0,100));d.entities=[a,b];const s=new PlanarEditSession(d,[a.id,b.id],{operation:'fillet'});s.set('radius',20);s.commit(d);assert.equal(d.entities.length,3);assert.equal(d.entities.at(-1).type,'ARC');near(d.entities.at(-1).r,20);});
test('negative scale, collapsed offset, wrong fillet inputs and unsafe bulge offsets are rejected',()=>{const {d,e}=fixture(circle(pt(0,0),20));const s=new PlanarEditSession(d,[e.id],{operation:'scale'});s.set('factor',-1);assert.throws(()=>s.evaluate());const o=new PlanarEditSession(d,[e.id],{operation:'offset'});o.set('amount',-20);assert.throws(()=>o.evaluate());assert.throws(()=>new PlanarEditSession(d,[e.id],{operation:'fillet'}));const p=polyline([{x:0,y:0,bulge:1},pt(100,0)],false);d.entities=[p];assert.throws(()=>new PlanarEditSession(d,[p.id],{operation:'offset'}));});
test('draft undo/redo and host history stay distinct',()=>{let d=createDocument();const e=line(pt(0,0),pt(100,0));d.entities=[e];const h=new History({capture:()=>d,restore:s=>{d=s;}}),s=new PlanarEditSession(d,[e.id]);const before=s.snapshot();s.set('length',150);s.checkpoint(before);assert.equal(s.undo(),true);near(s.value('length'),100);assert.equal(s.redo(),true);h.run('Visual edit',()=>s.commit(d));assert.equal(h.undoStack.length,1);near(d.entities[0].b.x,150);h.undo();near(d.entities[0].b.x,100);});
for(const change of [d=>d.name='Renamed',d=>d.parameters.other=4,d=>d.entities[0].b.x=250,d=>d.version++])test('full source guard rejects '+change,()=>{const {d,s}=fixture(line(pt(0,0),pt(100,0)));s.set('length',150);s.evaluate();change(d);const before=JSON.stringify(d);assert.throws(()=>s.commit(d),/changed/);assert.equal(JSON.stringify(d),before);});
test('separate document with matching JSON cannot receive a preview',()=>{const {d,s}=fixture(circle(pt(0,0),20));assert.throws(()=>s.commit(clone(d)),/changed/);s.cancel();assert.equal(s.source,null);assert.equal(s.base,null);assert.throws(()=>s.evaluate(),/ended/);});
for(const e of [entity('3DSOLID'),line(pt(0,0),pt(10,0),{locked:true}),line({x:0,y:0,z:1},pt(10,0)),circle(pt(0,0),5,{extrusion:{x:0,y:1,z:0}}),entity('DIMENSION',{dimtype:33,a:pt(0,0),b:pt(20,0)}),entity('HATCH',{associative:true}),entity('POLYLINE',{flags:64,points:[pt(0,0)]}),line(pt(0,0),pt(10,0),{model3dConsumed:true})])test('unsafe editing is explicitly guarded: '+JSON.stringify(e),()=>{const d=createDocument();d.entities=[e];assert.ok(planarEditable(e,d));assert.throws(()=>new PlanarEditSession(d,[e.id]));});
test('unknown fields, nonfinite values and long input are rejected',()=>{const {s}=fixture(circle(pt(0,0),20));assert.throws(()=>s.set('__proto__','x'));assert.throws(()=>s.set('radius','1'.repeat(16001)));for(const v of [NaN,Infinity,'1e20','x.constructor'])assert.throws(()=>number2(v,s.base));assert.throws(()=>handles2(s,0));assert.throws(()=>dragHandle2(s,{},pt(NaN,0),s.snapshot()));});
for(const writer of [writeDXF,writeDXFBinary])test(writer.name+' keeps edited native types and parametric values',()=>{const d=createDocument(),e=circle(pt(0,0),20);d.entities=[e];const s=new PlanarEditSession(d,[e.id]);s.set('radius','30');s.commit(d);const imported=parseDXF(writer(d));assert.equal(imported.entities[0].type,'CIRCLE');near(imported.entities[0].r,30);assert.equal(imported.entities[0].parametric.radius,'30');});
for(const origin of [0,1e8,1e10])test('3D measurement is world-space at origin '+origin,()=>{const m=measurePoints3(V3(origin,origin,origin),V3(origin+3,origin+4,origin+12));near(m.distance,13);near(m.horizontal,5);near(m.delta.z,12);near(m.midpoint.x,origin+1.5,1e-5);});
for(const n of [V3(1,0,0),V3(0,2,0),V3(1,2,3)])test('arbitrary section guide is coplanar '+JSON.stringify(n),()=>{const f=sectionFrame3(n,30,V3(100,50,-20),120);for(const p of f.corners)near(dot3(f.normal,p),f.offset);near(dot3(f.normal,f.u),0);near(dot3(f.u,f.v),0);near(distance3(f.corners[0],f.corners[1]),120);});
test('inspection mathematics rejects invalid planes and coordinates',()=>{assert.throws(()=>sectionFrame3(V3(),0));assert.throws(()=>sectionFrame3(V3(0,0,1),NaN));assert.throws(()=>sectionFrame3(V3(0,0,1),0,V3(),-1));assert.throws(()=>measurePoints3(V3(NaN,0,0),V3()));near(measurePoints3(V3(),V3()).distance,0);});
test('public restore rejects incomplete or foreign field snapshots without mutation',()=>{const {s}=fixture(circle(pt(0,0),20)),before=s.snapshot();for(const bad of [null,[],{}, {...before,unexpected:'30'},{...before,radius:{value:3}}]){assert.throws(()=>s.restore(bad),/Invalid/);assert.deepEqual(s.snapshot(),before);}});
test('copied block attributes receive separate stable native identities',()=>{const d=createDocument();d.blocks.B={name:'B',base:pt(0,0),entities:[line(pt(0,0),pt(20,0))],ports:[]};d.entities=[entity('INSERT',{id:'block',block:'B',x:0,y:0,sx:1,sy:1,attributes:[entity('ATTRIB',{id:'attr',p:pt(0,0),text:'User',height:10})]})];const s=new PlanarEditSession(d,['block'],{operation:'move'});s.set('copy',true);s.set('dx',20);s.evaluate();const id=s.preview.entities[1].attributes[0].id;s.set('dx',40);s.commit(d);assert.equal(d.entities[1].attributes[0].id,id);assert.notEqual(id,'attr');assert.equal(d.entities[0].attributes[0].id,'attr');});
test('elevated native dimension witnesses cannot be flattened through 2D editing',()=>{const d=createDocument(),e=entity('DIMENSION',{dimtype:36,definitionPoint:{x:0,y:0,z:4},defpoint4:{x:40,y:0,z:4},dimension:{version:1}});d.entities=[e];assert.throws(()=>new PlanarEditSession(d,[e.id]),/outside XY/);});

import { createVisualDraftingExample } from '../packages/workbench/src/visual-example2d.js';
test('visual workshop has native editable geometry, active constraints and managed dimensions',()=>{const d=createVisualDraftingExample();assert.equal(d.entities.length,15);assert.equal(d.constraints.length,1);assert.ok(d.blocks.AdjustableBar.dynamic);const s=new PlanarEditSession(d,['driven-edge'],{process:solve});s.set('length',160);s.commit(d);const e=d.entities.find(e=>e.id==='associated-length');near(distance3(e.a,e.b),160);});
test('visual workshop block grip updates its native parameter',()=>{const d=createVisualDraftingExample(),s=new PlanarEditSession(d,['adjustable-bar']);s.set('dynamic:Length',110);s.commit(d);near(d.entities.find(e=>e.id==='adjustable-bar').dynamicParameters.Length,110);});
