import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { VISUAL_STYLES } from '@conduitcad/renderer3d';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cards=[];
for (const style of VISUAL_STYLES) {
    const images=[];
    for(const backend of ['webgl2','canvas']) {
        const bytes=await readFile(`artifacts/render-${backend}-${style.id}.png`);
        images.push(`<img class="${backend}" src="data:image/png;base64,${bytes.toString('base64')}" alt="${escape(style.label)} rendered using ${backend}" loading="lazy" width="564" height="566">`);
    }
    cards.push(`<article><div class="heading"><span>${escape(style.group)}</span><h2>${escape(style.label)}</h2></div>${images.join('')}<p>${escape(style.description)}</p><code>${escape(style.id)}</code></article>`);
}
await mkdir('docs',{recursive:true});
await writeFile('docs/rendering-gallery.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ConduitCAD · 16 visual styles</title><style>
*{box-sizing:border-box}body{margin:0;background:#f0f5f5;color:#193e48;font:16px system-ui,sans-serif}header{max-width:1400px;margin:auto;padding:40px 24px 24px}h1{font-size:clamp(28px,4vw,46px);margin:8px 0}header p{max-width:900px;line-height:1.65}.eyebrow{color:#008375;text-transform:uppercase;letter-spacing:.12em;font-size:12px;font-weight:700}.controls{max-width:1400px;margin:auto;padding:0 24px 20px;display:flex;align-items:center;gap:20px;flex-wrap:wrap}.controls label{display:inline-flex;align-items:center;min-height:44px;gap:8px}input{width:20px;height:20px;accent-color:#008375}.grid{max-width:1400px;margin:auto;padding:0 24px 40px;display:grid;grid-template-columns:repeat(auto-fit,minmax(min(270px,100%),1fr));gap:18px}article{border:1px solid #c5d8d5;border-radius:12px;overflow:hidden;background:white;padding-bottom:18px}.heading{padding:16px 18px 8px}.heading span{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#567a73}h2{font-size:17px;margin:6px 0;min-height:40px}article img{display:block;width:100%;height:auto;aspect-ratio:564/566;object-fit:contain}article p,article code{margin:12px 18px;line-height:1.5}article p{font-size:13px;min-height:60px}code{font-size:12px;color:#3c7066}.canvas{display:none!important}body:has(#canvas:checked) .canvas{display:block!important}body:has(#canvas:checked) .webgl2{display:none!important}footer{max-width:1400px;margin:auto;padding:16px 24px 40px;font-size:13px;line-height:1.6}
</style><header><div class="eyebrow">ConduitCAD · Rendering checkpoint 0.10.0</div><h1>One model. Sixteen visual styles.</h1><p>Actual captured frames from the production renderer, with the same camera and geometry. Select the executed backend below. These images are not design mockups or unrelated illustrations. Open the application’s Display styles panel to use the same modes interactively.</p></header><div class="controls"><label><input id="webgl2" type="radio" name="backend" checked>WebGL2 · 4× MSAA</label><label><input id="canvas" type="radio" name="backend">Canvas · software depth</label></div><main class="grid">${cards.join('')}</main><footer>Chromium / SwiftShader software-adapter validation, not physical GPU qualification. The new WebGPU graph awaits native-origin execution and is deliberately not represented by a substituted image. Separate fixtures exercise shadows, ambient occlusion, transparent overlap, perspective clipping and section caps. See docs/VALIDATION_RENDERING_0100.md and artifacts/render-backends.json in the source workspace.</footer></html>`);
console.log(`Created offline rendering gallery with ${VISUAL_STYLES.length} styles and 32 real captured frames.`);
